### ISSUE TITLE
Can't paste μ in the REPL

### ISSUE THREAD

**Issue by Souravgoswami** [ruby/irb#142]
## Description
I can't seem to paste "μ" in the REPL, but other characters are working fine:
![image](https://user-images.githubusercontent.com/37468605/100267723-e71e4100-2f79-11eb-92fc-972f8f6985d0.png)

What are your expected behavior and actual behavior of your environment?

Pasting the character should print the character in the REPL. But it crashes the whole REPL.

Environment:
```
$ irb
irb(main):001:0> IRB::VERSION
=> "1.2.7"
```

```
$ irb
irb(main):001:0> puts ENV.map { |x| x.join(' => '.freeze) }
SHELL => /bin/bash
SESSION_MANAGER => local/archlinux:@/tmp/.ICE-unix/413,unix/archlinux:/tmp/.ICE-unix/413
TBBROOT => /opt/intel/compilers_and_libraries_2020.2.254/linux/tbb
PSTLROOT => SUBSTITUTE_INSTALL_DIR_HERE
COLORTERM => truecolor
XDG_CONFIG_DIRS => /etc/xdg
XDG_MENU_PREFIX => xfce-
HISTSIZE => 10000000000
SSH_AUTH_SOCK => /tmp/ssh-4zpcDQzVV7bB/agent.519
DESKTOP_SESSION => Xfce Session
SSH_AGENT_PID => 520
EDITOR => nano
GTK_MODULES => canberra-gtk-module:canberra-gtk-module
XDG_SEAT => seat0
PWD => /home/sourav
LOGNAME => sourav
XDG_SESSION_TYPE => x11
PANEL_GDK_CORE_DEVICE_EVENTS => 0
XAUTHORITY => /home/sourav/.Xauthority
MOTD_SHOWN => pam
HOME => /home/sourav
LANG => en_GB.UTF-8
XDG_CURRENT_DESKTOP => XFCE
VTE_VERSION => 6201
INVOCATION_ID => a95c0269eab3409bada099ea4fd75b62
XDG_SESSION_CLASS => user
TERM => xterm-256color
USER => sourav
LIBRARY_PATH => /opt/intel/compilers_and_libraries_2020.2.254/linux/tbb/lib/intel64/gcc4.8
VISUAL => nano
DISPLAY => :0.0
SHLVL => 1
XDG_VTNR => 7
XDG_SESSION_ID => 1
TILIX_ID => ea40486d-9d0f-4770-a3bf-c2c4caecef61
XDG_RUNTIME_DIR => /run/user/1000
LC_ALL => en_GB.UTF-8
JOURNAL_STREAM => 8:24518
XDG_DATA_DIRS => /usr/local/share:/usr/share
NLSPATH => /opt/intel/compilers_and_libraries_2020.2.254/linux/compiler/lib/intel64/locale/%l_%t/%N
PATH => /opt/intel/compilers_and_libraries_2020.2.254/linux/bin/intel64:/opt/intel/compilers_and_libraries_2020.2.254/linux/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/intel/bin:/opt/intel/inspector_2020.2.0.604588/bin64:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/sourav/.rvm/bin
HISTFILESIZE => 10000000000
DBUS_SESSION_BUS_ADDRESS => unix:path=/run/user/1000/bus
MAIL => /var/spool/mail/sourav
INTEL_LICENSE_FILE => /opt/intel/licenses
CPATH => SUBSTITUTE_INSTALL_DIR_HERE/include:SUBSTITUTE_INSTALL_DIR_HERE/stdlib:/opt/intel/compilers_and_libraries_2020.2.254/linux/tbb/include
RUBYOPT => -W0
_ => /usr/local/bin/irb
=> nil
```
```
$ irb
irb(main):001:0> RbConfig::CONFIG['CFLAGS']
=> "-O3 -pipe -fno-plt -march=native -mtune=native -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wdivision-by-zero -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wshorten-64-to-32 -Wwrite-strings -Wmissing-noreturn -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wunused-variable -Wextra-tokens"
```

```
$ irb
irb(main):002:0> [RUBY_PLATFORM, RUBY_VERSION, RUBY_ENGINE]
=> ["x86_64-linux", "2.7.1", "ruby"]
```

## Terminal Emulator
All are affected.

## Setting Files

```
$ cat ~/.irbrc 
{
        USE_COLORIZE: true,
        SAVE_HISTORY: 10 ** 6,
        SINGLE_IRB: true,
#       VERBOSE: true
}
.each { |x| IRB.conf[x[0]] = x[1] }
```

**Comment by nobu** [comment]
I can’t reproduce it with irb bundled with ruby 2.7.2 and master.

**Comment by Souravgoswami** [comment]
2.7.2 is the latest version, I installed it and I am getting the error... No matter what the locale is set, it always happens on my system.

The error I get is:
```
irb(main):001:0> Traceback (most recent call last):
	41: from /usr/local/bin/irb:23:in `<main>'
	40: from /usr/local/bin/irb:23:in `load'
	39: from /usr/local/lib/ruby/gems/2.7.0/gems/irb-1.2.7/exe/irb:11:in `<top (required)>'
	38: from /usr/local/lib/ruby/gems/2.7.0/gems/irb-1.2.7/lib/irb.rb:400:in `start'
	37: from /usr/local/lib/ruby/gems/2.7.0/gems/irb-1.2.7/lib/irb.rb:471:in `run'
	36: from /usr/local/lib/ruby/gems/2.7.0/gems/irb-1.2.7/lib/irb.rb:471:in `catch'
	35: from /usr/local/lib/ruby/gems/2.7.0/gems/irb-1.2.7/lib/irb.rb:472:in `block in run'
	34: from /usr/local/lib/ruby/gems/2.7.0/gems/irb-1.2.7/lib/irb.rb:537:in `eval_input'
	33: from /usr/local/lib/ruby/gems/2.7.0/gems/irb-1.2.7/lib/irb/ruby-lex.rb:150:in `each_top_level_statement'
	32: from /usr/local/lib/ruby/gems/2.7.0/gems/irb-1.2.7/lib/irb/ruby-lex.rb:150:in `catch'
	31: from /usr/local/lib/ruby/gems/2.7.0/gems/irb-1.2.7/lib/irb/ruby-lex.rb:151:in `block in each_top_level_statement'
	30: from /usr/local/lib/ruby/gems/2.7.0/gems/irb-1.2.7/lib/irb/ruby-lex.rb:151:in `loop'
	29: from /usr/local/lib/ruby/gems/2.7.0/gems/irb-1.2.7/lib/irb/ruby-lex.rb:154:in `block (2 levels) in each_top_level_statement'
	28: from /usr/local/lib/ruby/gems/2.7.0/gems/irb-1.2.7/lib/irb/ruby-lex.rb:182:in `lex'
	27: from /usr/local/lib/ruby/gems/2.7.0/gems/irb-1.2.7/lib/irb.rb:518:in `block in eval_input'
	26: from /usr/local/lib/ruby/gems/2.7.0/gems/irb-1.2.7/lib/irb.rb:704:in `signal_status'
	25: from /usr/local/lib/ruby/gems/2.7.0/gems/irb-1.2.7/lib/irb.rb:519:in `block (2 levels) in eval_input'
	24: from /usr/local/lib/ruby/gems/2.7.0/gems/irb-1.2.7/lib/irb/input-method.rb:294:in `gets'
	23: from /usr/local/lib/ruby/2.7.0/forwardable.rb:235:in `readmultiline'
	22: from /usr/local/lib/ruby/2.7.0/forwardable.rb:235:in `readmultiline'
	21: from /usr/local/lib/ruby/gems/2.7.0/gems/reline-0.1.8/lib/reline.rb:175:in `readmultiline'
	20: from /usr/local/lib/ruby/gems/2.7.0/gems/reline-0.1.8/lib/reline.rb:239:in `inner_readline'
	19: from /usr/local/lib/ruby/gems/2.7.0/gems/reline-0.1.8/lib/reline.rb:239:in `loop'
	18: from /usr/local/lib/ruby/gems/2.7.0/gems/reline-0.1.8/lib/reline.rb:241:in `block in inner_readline'
	17: from /usr/local/lib/ruby/gems/2.7.0/gems/reline-0.1.8/lib/reline.rb:276:in `read_io'
	16: from /usr/local/lib/ruby/gems/2.7.0/gems/reline-0.1.8/lib/reline.rb:276:in `loop'
	15: from /usr/local/lib/ruby/gems/2.7.0/gems/reline-0.1.8/lib/reline.rb:317:in `block in read_io'
	14: from /usr/local/lib/ruby/gems/2.7.0/gems/reline-0.1.8/lib/reline.rb:242:in `block (2 levels) in inner_readline'
	13: from /usr/local/lib/ruby/gems/2.7.0/gems/reline-0.1.8/lib/reline.rb:242:in `each'
	12: from /usr/local/lib/ruby/gems/2.7.0/gems/reline-0.1.8/lib/reline.rb:243:in `block (3 levels) in inner_readline'
	11: from /usr/local/lib/ruby/gems/2.7.0/gems/reline-0.1.8/lib/reline/line_editor.rb:879:in `input_key'
	10: from /usr/local/lib/ruby/gems/2.7.0/gems/reline-0.1.8/lib/reline/line_editor.rb:835:in `normal_char'
	 9: from /usr/local/lib/ruby/gems/2.7.0/gems/reline-0.1.8/lib/reline/line_editor.rb:800:in `process_key'
	 8: from /usr/local/lib/ruby/gems/2.7.0/gems/reline-0.1.8/lib/reline/line_editor.rb:725:in `run_for_operators'
	 7: from /usr/local/lib/ruby/gems/2.7.0/gems/reline-0.1.8/lib/reline/line_editor.rb:801:in `block in process_key'
	 6: from /usr/local/lib/ruby/gems/2.7.0/gems/reline-0.1.8/lib/reline/line_editor.rb:742:in `wrap_method_call'
	 5: from /usr/local/lib/ruby/gems/2.7.0/gems/reline-0.1.8/lib/reline/line_editor.rb:1127:in `process_insert'
	 4: from /usr/local/lib/ruby/gems/2.7.0/gems/reline-0.1.8/lib/reline/unicode.rb:126:in `calculate_width'
	 3: from /usr/local/lib/ruby/gems/2.7.0/gems/reline-0.1.8/lib/reline/unicode.rb:126:in `inject'
	 2: from /usr/local/lib/ruby/gems/2.7.0/gems/reline-0.1.8/lib/reline/unicode.rb:126:in `each'
	 1: from /usr/local/lib/ruby/gems/2.7.0/gems/reline-0.1.8/lib/reline/unicode.rb:127:in `block in calculate_width'
/usr/local/lib/ruby/gems/2.7.0/gems/reline-0.1.8/lib/reline/unicode.rb:97:in `get_mbchar_width': undefined method `[]' for nil:NilClass (NoMethodError)
```

**Comment by Souravgoswami** [comment]
Quite interesting, I got a Ruby from my linux distributor's repository now. It's working fine, but my compiled Ruby is crashing. Not sure why that might be...
