### ISSUE TITLE
IRB Crashing Inside Reline Gem When Backspacing an Empty Line of a Multiline Copy and Paste

### ISSUE THREAD

**Issue by gwillcox-r7** [ruby/irb#192]
## Description

IRB crashes when trying to backspace an empty line after copying and pasting a multiline statement.

```
3.0.0 :121 > class Temperature
3.0.0 :122 > 
3.0.0 :123 >   def Temperature.c2f(celsius)
3.0.0 :124 > 
3.0.0 :125 >     celsius * 9.0 / 5 + 32
3.0.0 :126 > 
3.0.0 :127 >   end
3.0.0 :128 > 
3.0.0 :129 >   def Temperature.f2c(fahrenheit)
3.0.0 :130 >     (fahrenheit - 32) * 5 / 9.0
3.0.0 :131 >                                /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/reline/line_editor.rb:1302:in `byteslice!': no implicit conversion of nil into String (TypeError)
3.0.0 :1from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/reline/line_editor.rb:1931:in `em_delete_prev_char'
3.0.0 :1from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/reline/line_editor.rb:951:in `call'
	from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/reline/line_editor.rb:951:in `wrap_method_call'
	from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/reline/line_editor.rb:998:in `block in process_key'
	from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/reline/line_editor.rb:997:in `process_key'
	from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/reline/line_editor.rb:1032:in `normal_char'
	from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/reline/line_editor.rb:1078:in `input_key'
	from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/reline.rb:247:in `block (3 levels) in inner_readline'
	from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/reline.rb:246:in `each'
	from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/reline.rb:246:in `block (2 levels) in inner_readline'
	from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/reline.rb:284:in `loop'
	from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/reline.rb:284:in `read_io'
	from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/reline.rb:245:in `block in inner_readline'
	from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/reline.rb:243:in `loop'
	from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/reline.rb:243:in `inner_readline'
	from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/reline.rb:175:in `readmultiline'
	from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/forwardable.rb:238:in `readmultiline'
	from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/forwardable.rb:238:in `readmultiline'
	from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/irb/input-method.rb:302:in `gets'
	from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/irb.rb:519:in `block (2 levels) in eval_input'
	from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/irb.rb:721:in `signal_status'
	from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/irb.rb:518:in `block in eval_input'
	from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/irb/ruby-lex.rb:202:in `lex'
	from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/irb/ruby-lex.rb:174:in `block (2 levels) in each_top_level_statement'
	from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/irb/ruby-lex.rb:171:in `loop'
	from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/irb/ruby-lex.rb:171:in `block in each_top_level_statement'
	from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/irb/ruby-lex.rb:170:in `catch'
	from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/irb/ruby-lex.rb:170:in `each_top_level_statement'
	from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/irb.rb:537:in `eval_input'
	from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/irb.rb:472:in `block in run'
	from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/irb.rb:471:in `catch'
	from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/irb.rb:471:in `run'
	from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/irb.rb:400:in `start'
	from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/irb-1.3.0/exe/irb:11:in `<top (required)>'
	from /usr/share/rvm/rubies/ruby-3.0.0/bin/irb:23:in `load'
	from /usr/share/rvm/rubies/ruby-3.0.0/bin/irb:23:in `<main>'
```

This may be more of a `reline` error than a IRB error but it was odd to see this occurring with minimal changes beyond using IRB normally.

## Result of irb_info

```
3.0.0 :001 > irb_info
 => 
Ruby version: 3.0.0
IRB version: irb 1.3.0 (2020-12-25)
InputMethod: ReidlineInputMethod with Reline 0.2.0
.irbrc path: /usr/share/rvm/rubies/ruby-3.0.0/.irbrc
 
3.0.0 :002 > 
```

## Terminal Emulator

OhMyZSH

## Setting Files

Are you using `~/.irbrc` and `~/.inputrc`?

No I am not.

**Comment by aycabta** [comment]
Would you run `gem install irb reline` to install the latest version of the `irb gem` and the `reline gem`? I think the bug has been fixed.

**Comment by gwillcox-r7** [comment]
Thanks @aycabta you are right this has been fixed in the latest versions, should have checked for that first but used to using Ruby 2.7.2 for my work so I forgot to update the Gems for Ruby 3.0.0 first. Closing this issue as this is fixed in latest versions.
