### ISSUE TITLE
NoMethod error raised on invalid syntax

### ISSUE THREAD

**Issue by MatheusRich** [ruby/irb#226]
## Description
When I open `irb` and type

```ruby
{a: { b: c: 1}
```
IRB raises a `NoMethodError`. I was expecting a `SyntaxError (syntax error, unexpected tLABEL)` here.

Full Stacktrace:
```
Traceback (most recent call last):
	33: from /home/matheus/.rbenv/versions/2.7.2/bin/irb:23:in `<main>'
	32: from /home/matheus/.rbenv/versions/2.7.2/bin/irb:23:in `load'
	31: from /home/matheus/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.3.0/exe/irb:11:in `<top (required)>'
	30: from /home/matheus/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.3.0/lib/irb.rb:400:in `start'
	29: from /home/matheus/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.3.0/lib/irb.rb:471:in `run'
	28: from /home/matheus/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.3.0/lib/irb.rb:471:in `catch'
	27: from /home/matheus/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.3.0/lib/irb.rb:472:in `block in run'
	26: from /home/matheus/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.3.0/lib/irb.rb:537:in `eval_input'
	25: from /home/matheus/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.3.0/lib/irb/ruby-lex.rb:170:in `each_top_level_statement'
	24: from /home/matheus/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.3.0/lib/irb/ruby-lex.rb:170:in `catch'
	23: from /home/matheus/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.3.0/lib/irb/ruby-lex.rb:171:in `block in each_top_level_statement'
	22: from /home/matheus/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.3.0/lib/irb/ruby-lex.rb:171:in `loop'
	21: from /home/matheus/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.3.0/lib/irb/ruby-lex.rb:174:in `block (2 levels) in each_top_level_statement'
	20: from /home/matheus/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.3.0/lib/irb/ruby-lex.rb:202:in `lex'
	19: from /home/matheus/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.3.0/lib/irb.rb:518:in `block in eval_input'
	18: from /home/matheus/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.3.0/lib/irb.rb:721:in `signal_status'
	17: from /home/matheus/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.3.0/lib/irb.rb:519:in `block (2 levels) in eval_input'
	16: from /home/matheus/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.3.0/lib/irb/input-method.rb:302:in `gets'
	15: from /home/matheus/.rbenv/versions/2.7.2/lib/ruby/2.7.0/forwardable.rb:235:in `readmultiline'
	14: from /home/matheus/.rbenv/versions/2.7.2/lib/ruby/2.7.0/forwardable.rb:235:in `readmultiline'
	13: from /home/matheus/.rbenv/versions/2.7.2/lib/ruby/2.7.0/reline.rb:175:in `readmultiline'
	12: from /home/matheus/.rbenv/versions/2.7.2/lib/ruby/2.7.0/reline.rb:238:in `inner_readline'
	11: from /home/matheus/.rbenv/versions/2.7.2/lib/ruby/2.7.0/reline.rb:238:in `loop'
	10: from /home/matheus/.rbenv/versions/2.7.2/lib/ruby/2.7.0/reline.rb:239:in `block in inner_readline'
	 9: from /home/matheus/.rbenv/versions/2.7.2/lib/ruby/2.7.0/reline.rb:270:in `read_io'
	 8: from /home/matheus/.rbenv/versions/2.7.2/lib/ruby/2.7.0/reline.rb:270:in `loop'
	 7: from /home/matheus/.rbenv/versions/2.7.2/lib/ruby/2.7.0/reline.rb:311:in `block in read_io'
	 6: from /home/matheus/.rbenv/versions/2.7.2/lib/ruby/2.7.0/reline.rb:240:in `block (2 levels) in inner_readline'
	 5: from /home/matheus/.rbenv/versions/2.7.2/lib/ruby/2.7.0/reline.rb:240:in `each'
	 4: from /home/matheus/.rbenv/versions/2.7.2/lib/ruby/2.7.0/reline.rb:242:in `block (3 levels) in inner_readline'
	 3: from /home/matheus/.rbenv/versions/2.7.2/lib/ruby/2.7.0/reline/line_editor.rb:345:in `rerender'
	 2: from /home/matheus/.rbenv/versions/2.7.2/lib/ruby/2.7.0/reline/line_editor.rb:85:in `check_multiline_prompt'
	 1: from /home/matheus/.rbenv/versions/2.7.2/lib/ruby/2.7.0/reline/line_editor.rb:1058:in `calculate_width'
/home/matheus/.rbenv/versions/2.7.2/lib/ruby/2.7.0/reline/unicode.rb:97:in `calculate_width': undefined method `encode' for nil:NilClass (NoMethodError)
```

## Result of irb_info

```
irb(main):001:0> irb_info
=>
Ruby version: 2.7.2
IRB version: irb 1.3.0 (2020-12-25)
InputMethod: ReidlineInputMethod with Reline 0.1.5
```

## Terminal Emulator

What's your terminal emulator?

## Setting Files

None

**Comment by aycabta** [comment]
Could you run `gem install irb reline` and try again?

**Comment by MatheusRich** [comment]
That worked! Thanks.
