### ISSUE TITLE
Unexpected multibyte error message is displayed

### ISSUE THREAD

**Issue by koic** [ruby/irb#229]
## Description

The following is an unexpected RDBMS error message.

```console
% bin/rails c
Running via Spring preloader in process 72443
Loading development environment (Rails 6.1.3.1)
irb(main):001:0> ActiveRecord::Base.connection.truncate(:table_name)
   (2.0ms)  TRUNCATE TABLE "TABLE_NAME"
stmt.c:267:in oci8lib_300.bundle: OCIError: ORA-00942: \xE8\xA1\xA8\xE3\x81\xBE\xE3\x81\x9F\xE3\x81\xAF\xE3\x83\x93\xE3\x83\xA5\xE3\x83\xBC\xE3\x81\x8C\xE5\xAD\x98\xE5\x9C\xA8\xE3\x81\x97\xE3\x81\xBE\xE3\x81\x9B\xE3\x82\x93\xE3\x80\x82 (ActiveRecord::StatementInvalid)
stmt.c:267:in oci8lib_300.bundle: ORA-00942: \xE8\xA1\xA8\xE3\x81\xBE\xE3\x81\x9F\xE3\x81\xAF\xE3\x83\x93\xE3\x83\xA5\xE3\x83\xBC\xE3\x81\x8C\xE5\xAD\x98\xE5\x9C\xA8\xE3\x81\x97\xE3\x81\xBE\xE3\x81\x9B\xE3\x82\x93\xE3\x80\x82 (OCIError)
```

And the following is encoded to the expected message.

```console
irb(main):002:0> "ORA-00942: \xE8\xA1\xA8\xE3\x81\xBE\xE3\x81\x9F\xE3\x81\xAF\xE3\x83\x93\xE3\x83\xA5\xE3\x83\xBC\xE3\x81\x8C\xE5\xAD\x98\xE5\x9C\xA8\xE3\x81\x97\xE3\x81\xBE\xE3\x81\x9B\xE3\x82\x93\xE3\x80\x82".encode('UTF-8')
=> "ORA-00942: 表またはビューが存在しません。"
```

Pry is displaying the expected message, so it seems that REPL has a cause.

## Result of irb_info

Please past the result of `irb_info` command in IRB.

```console
irb(main):003:0> irb_info
=>
Ruby version: 3.0.1
IRB version: irb 1.3.5 (2021-04-03)
InputMethod: ReidlineInputMethod with Reline 0.2.5 and /Users/koic/.inputrc
.irbrc path: /Users/koic/.irbrc
RUBY_PLATFORM: x86_64-darwin19
```

## Terminal Emulator

iTerm2 Build 3.0.15

## Setting Files

```console
% cat /Users/koic/.irbrc
IRB.conf[:AUTO_INDENT] = true
IRB.conf[:SAVE_HISTORY] = 2000
IRB.conf[:HISTORY_PATH] = File.expand_path('~/.irb-history')
```

**Comment by koic** [comment]
Additional information. It seems that the string contained in object representation when using natto / Mecab is also different between IRB and Pry.

natto: https://github.com/buruzaemon/natto

## IRB

### Object representation

`undefined method 'undefined_method' for #<Natto::MeCabNode:0x00007fbd62a04ac0 @pointer=#<FFI::Pointer address=0x00007fbd08028070>, stat=0, @surface="\xE3\x81\x82", @feature="\xE3\x83\x95\xE3\x82\xA3\xE3\x83\xA9\xE3\x83\xBC,*,*,*,*,*,\xE3\x81\x82,\xE3\x82\xA2,\xE3\x82\xA2"> (NoMethodError)`

### Reproduction steps

```console
% irb
irb(main):001:0> require 'natto'
=> true
irb(main):002:0> nm = Natto::MeCab.new
=> #<Natto::MeCab:0x00007fbd430b56a0 @model=#<FFI::Pointer address=0x00007fbd625389b0>, @tagger=#<FFI::Pointer address=0x00007fbd625470f0>, @lattice=#<FFI::Pointer address=0x00007fbd6254adb0>, ...
irb(main):003:0> nm.parse('あいう') { |n| n.undefined_method }
/Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/natto-1.2.0/lib/natto/natto.rb:423:in `rescue in block (2 levels) in initialize': MECAB_NBEST request type is not set (Natto::MeCabError)
        from /Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/natto-1.2.0/lib/natto/natto.rb:347:in `block (2 levels) in initialize'
        from /Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/natto-1.2.0/lib/natto/natto.rb:480:in `each'
        from /Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/natto-1.2.0/lib/natto/natto.rb:480:in `each'
        from /Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/natto-1.2.0/lib/natto/natto.rb:480:in `parse'
        from (irb):3:in `<main>'
        from /Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/irb-1.3.5/exe/irb:13:in `<top (required)>'
        from /Users/koic/.rbenv/versions/3.0.1/bin/irb:23:in `load'
        from /Users/koic/.rbenv/versions/3.0.1/bin/irb:23:in `<main>'
/Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/natto-1.2.0/lib/natto/struct.rb:20:in `rescue in method_missing': undefined method 'undefined_method' for #<Natto::MeCabNode:0x00007fbd62a04ac0 @pointer=#<FFI::Pointer address=0x00007fbd08028070>, stat=0, @surface="\xE3\x81\x82", @feature="\xE3\x83\x95\xE3\x82\xA3\xE3\x83\xA9\xE3\x83\xBC,*,*,*,*,*,\xE3\x81\x82,\xE3\x82\xA2,\xE3\x82\xA2"> (NoMethodError)
        from /Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/natto-1.2.0/lib/natto/struct.rb:16:in `method_missing'
        from (irb):3:in `block in <main>'
        from /Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/natto-1.2.0/lib/natto/natto.rb:480:in `block in parse'
        from /Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/natto-1.2.0/lib/natto/natto.rb:413:in `yield'
        from /Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/natto-1.2.0/lib/natto/natto.rb:413:in `block (3 levels) in initialize'
        from /Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/natto-1.2.0/lib/natto/natto.rb:400:in `times'
        from /Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/natto-1.2.0/lib/natto/natto.rb:400:in `block (2 levels) in initialize'
        from /Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/natto-1.2.0/lib/natto/natto.rb:480:in `each'
        from /Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/natto-1.2.0/lib/natto/natto.rb:480:in `each'
        from /Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/natto-1.2.0/lib/natto/natto.rb:480:in `parse'
        from (irb):3:in `<main>'
        from /Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/irb-1.3.5/exe/irb:13:in `<top (required)>'
        from /Users/koic/.rbenv/versions/3.0.1/bin/irb:23:in `load'
        from /Users/koic/.rbenv/versions/3.0.1/bin/irb:23:in `<main>'
/Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/natto-1.2.0/lib/natto/struct.rb:18:in `[]': No such field 'undefined_method' (ArgumentError)
        from /Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/natto-1.2.0/lib/natto/struct.rb:18:in `method_missing'
        from (irb):3:in `block in <main>'
        from /Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/natto-1.2.0/lib/natto/natto.rb:480:in `block in parse'
        from /Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/natto-1.2.0/lib/natto/natto.rb:413:in `yield'
        from /Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/natto-1.2.0/lib/natto/natto.rb:413:in `block (3 levels) in initialize'
        from /Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/natto-1.2.0/lib/natto/natto.rb:400:in `times'
        from /Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/natto-1.2.0/lib/natto/natto.rb:400:in `block (2 levels) in initialize'
        from /Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/natto-1.2.0/lib/natto/natto.rb:480:in `each'
        from /Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/natto-1.2.0/lib/natto/natto.rb:480:in `each'
        from /Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/natto-1.2.0/lib/natto/natto.rb:480:in `parse'
        from (irb):3:in `<main>'
        from /Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/irb-1.3.5/exe/irb:13:in `<top (required)>'
        from /Users/koic/.rbenv/versions/3.0.1/bin/irb:23:in `load'
        from /Users/koic/.rbenv/versions/3.0.1/bin/irb:23:in `<main>'
```

## Pry

### Object representation

`undefined method 'undefined_method' for #<Natto::MeCabNode:0x00007fa0908489c8 @pointer=#<FFI::Pointer address=0x00007fa078028070>, stat=0, @surface="あ", @feature="フィラー,*,*,*,*,*,あ,ア,ア">`

### Reproduction steps

```console
% pry
[1] pry(main)> require 'natto'
=> true
[2] pry(main)> nm = Natto::MeCab.new
=> #<Natto::MeCab:0x00007fa090810668 @model=#<FFI::Pointer address=0x00007fa0c07998c0>, @tagger=#<FFI::Pointer address=0x00007fa0c0799fd0>, @lattice=#<FFI::Pointer address=0x00007fa0c0799360>, @libpath="/usr/local/Cellar/mecab/0.996/lib/libmecab.dylib", @options={}, @dicts=[#<Natto::DictionaryInfo:0x00007fa09117eee8 @filepath="/usr/local/lib/mecab/dic/ipadic/sys.dic", charset=utf8, type=0>], @version=0.996>
[3] pry(main)> nm.parse('あいう') { |n| n.undefined_method }
Natto::MeCabError: MECAB_NBEST request type is not set
from /Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/natto-1.2.0/lib/natto/natto.rb:423:in `rescue in block (2 levels) in initialize'
Caused by NoMethodError: undefined method 'undefined_method' for #<Natto::MeCabNode:0x00007fa0908489c8 @pointer=#<FFI::Pointer address=0x00007fa078028070>, stat=0, @surface="あ", @feature="フィラー,*,*,*,*,*,あ,ア,ア">
from /Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/natto-1.2.0/lib/natto/struct.rb:20:in `rescue in method_missing'
Caused by ArgumentError: No such field 'undefined_method'
from /Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/natto-1.2.0/lib/natto/struct.rb:18:in `[]'
```

**Comment by osyo-manga** [comment]
This problem is reproduced since irb 1.3.1.

## irb 1.3.0

```
$ irb
irb(main):001:0> irb_info
=> 
Ruby version: 3.0.0
IRB version: irb 1.3.0 (2020-12-25)
InputMethod: ReidlineInputMethod with Reline 0.2.0 and /home/worker/.inputrc
.irbrc path: /home/worker/.irbrc

irb(main):002:0> Object.new.tap { |it| it.instance_eval { @value = "あああ" } }.hoge
Traceback (most recent call last):
        4: from /home/worker/.rbenv/versions/3.0.0/bin/irb:23:in `<main>'
        3: from /home/worker/.rbenv/versions/3.0.0/bin/irb:23:in `load'
        2: from /home/worker/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/irb-1.3.0/exe/irb:11:in `<top (required)>'
        1: from (irb):2:in `<main>'
NoMethodError (undefined method `hoge' for #<Object:0x000055b8059bf768 @value="あああ">)
irb(main):003:0>
```

## irb 1.3.0

```
$ irb
irb(main):001:0> irb_info
=> 
Ruby version: 3.0.0
IRB version: irb 1.3.1 (2021-01-12)
InputMethod: ReidlineInputMethod with Reline 0.2.0 and /home/worker/.inputrc
.irbrc path: /home/worker/.irbrc

irb(main):002:0> Object.new.tap { |it| it.instance_eval { @value = "あああ" } }.hoge
(irb):2:in `<main>': undefined method `hoge' for #<Object:0x0000556429880a80 @value="\xE3\x81\x82\xE3\x81\x82\xE3\x81\x82"> (NoMethodError)
	from /home/worker/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/irb-1.3.1/exe/irb:11:in `<top (required)>'
	from /home/worker/.rbenv/versions/3.0.0/bin/irb:23:in `load'
	from /home/worker/.rbenv/versions/3.0.0/bin/irb:23:in `<main>'
irb(main):003:0> 
```
