### ISSUE TITLE
Getting `nil can't be coerced into Integer` when assigning a value with international characters

### ISSUE THREAD

**Issue by jorgemanrubia** [ruby/irb#261]
## Description

When running irb with the `--nomultiline` flag, trying to assign a string with accents shows an error:

```
$ irb --nomultiline
>> foo="bár"
Traceback (most recent call last):
       16: from /Users/jorge/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
       15: from /Users/jorge/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.24/lib/bundler/cli.rb:31:in `dispatch'
       14: from /Users/jorge/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
       13: from /Users/jorge/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
       12: from /Users/jorge/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
       11: from /Users/jorge/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.24/lib/bundler/cli.rb:475:in `exec'
       10: from /Users/jorge/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.24/lib/bundler/cli/exec.rb:28:in `run'
        9: from /Users/jorge/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.24/lib/bundler/cli/exec.rb:63:in `kernel_load'
        8: from /Users/jorge/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.24/lib/bundler/cli/exec.rb:63:in `load'
        7: from /Users/jorge/.rbenv/versions/2.7.2/bin/irb:23:in `<top (required)>'
        6: from /Users/jorge/.rbenv/versions/2.7.2/bin/irb:23:in `load'
        5: from /Users/jorge/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.2.6/exe/irb:11:in `<top (required)>'
        4: from /Users/jorge/.rbenv/versions/2.7.2/lib/ruby/2.7.0/reline/unicode.rb:99:in `calculate_width'
        3: from /Users/jorge/.rbenv/versions/2.7.2/lib/ruby/2.7.0/reline/unicode.rb:99:in `scan'
        2: from /Users/jorge/.rbenv/versions/2.7.2/lib/ruby/2.7.0/reline/unicode.rb:108:in `block in calculate_width'
        1: from /Users/jorge/.rbenv/versions/2.7.2/lib/ruby/2.7.0/reline/unicode.rb:108:in `+'
TypeError (nil can't be coerced into Integer)
```

Everything seems to work fine, the variable gets assigned, you just see the error.

## Result of irb_info

```
>> irb_info
=>
Ruby version: 2.7.2
IRB version: irb 1.2.6 (2020-09-14)
InputMethod: ReadlineInputMethod with ext/readline 8.1 and /Users/jorge/.inputrc
.irbrc path: /Users/jorge/.irbrc
```

## Terminal Emulator

Oh-my-zsh. Getting the same result with bash.

## Setting Files

Are you using `~/.irbrc` and `~/.inputrc`?

I can reproduce without any setting file.

**Comment by ima1zumi** [comment]
Would you run `gem install irb reline` to install the latest version of `irb gem` and `reline gem`? I think the bug has been fixed.

**Comment by jorgemanrubia** [comment]
Thanks @ima1zumi. That fixed the problem 👍👍.
