### ISSUE TITLE
Assigning variable gives me an error (`winsize': Bad file descriptor (Errno::EBADF)) on Emacs

### ISSUE THREAD

**Issue by Evotron** [ruby/irb#266]
## Description

When I assign a number to a variable, I get the following error:

```
I:/Ruby30-x64/lib/ruby/3.0.0/irb/input-method.rb:42:in `winsize': Bad file descriptor (Errno::EBADF)
	from I:/Ruby30-x64/lib/ruby/3.0.0/irb/input-method.rb:42:in `winsize'
	from I:/Ruby30-x64/lib/ruby/3.0.0/irb.rb:800:in `output_value'
	from I:/Ruby30-x64/lib/ruby/3.0.0/irb.rb:572:in `block (2 levels) in eval_input'
	from I:/Ruby30-x64/lib/ruby/3.0.0/irb.rb:751:in `signal_status'
	from I:/Ruby30-x64/lib/ruby/3.0.0/irb.rb:548:in `block in eval_input'
	from I:/Ruby30-x64/lib/ruby/3.0.0/irb/ruby-lex.rb:251:in `block (2 levels) in each_top_level_statement'
	from I:/Ruby30-x64/lib/ruby/3.0.0/irb/ruby-lex.rb:233:in `loop'
	from I:/Ruby30-x64/lib/ruby/3.0.0/irb/ruby-lex.rb:233:in `block in each_top_level_statement'
	from I:/Ruby30-x64/lib/ruby/3.0.0/irb/ruby-lex.rb:232:in `catch'
	from I:/Ruby30-x64/lib/ruby/3.0.0/irb/ruby-lex.rb:232:in `each_top_level_statement'
	from I:/Ruby30-x64/lib/ruby/3.0.0/irb.rb:547:in `eval_input'
	from I:/Ruby30-x64/lib/ruby/3.0.0/irb.rb:481:in `block in run'
	from I:/Ruby30-x64/lib/ruby/3.0.0/irb.rb:480:in `catch'
	from I:/Ruby30-x64/lib/ruby/3.0.0/irb.rb:480:in `run'
	from I:/Ruby30-x64/lib/ruby/3.0.0/irb.rb:409:in `start'
	from I:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/irb-1.3.5/exe/irb:11:in `<top (required)>'
	from I:/Ruby30-x64/bin/irb.cmd:31:in `load'
	from I:/Ruby30-x64/bin/irb.cmd:31:in `<main>'
Maybe IRB bug!
```

I’m expecting no error at all and just the number I’ve assigned the variable to. The variable works properly… but I get the error message.

## Result of irb_info

```
Ruby version: 3.0.2
IRB version: irb 1.3.5 (2021-04-03)
InputMethod: StdioInputMethod
.irbrc path: C:/Users/Alejandro/.irbrc
RUBY_PLATFORM: x64-mingw32
```

## Terminal Emulator

I’m using GNU Emacs 27.2 on Windows 10.   This happens even when I switch from the default Windows Command Prompt in Emacs to Powershell in Emacs.

This doesn’t happen when I assign variables in native Windows Command Prompt, Windows Terminal, or Windows Powershell—just Emacs’s native shell on Windows.

## Setting Files

I’m not using `~/.irbrc` or `~/.inputrc`.

**Comment by aycabta** [comment]
I can't reproduce it on my Emacs, but it's on Emacs within the Linux terminal.

Would you tell me all logs including all commands as you typed into the IRB started within Emacs?

**Comment by Evotron** [comment]
FIXED on the latest version of IRB!!

Thank you. 

use this: `irb --inf-ruby-mode`
