### ISSUE TITLE
unmatched close parenthesis: (RegexpError)     

### ISSUE THREAD

**Issue by eregon** [ruby/irb#299]
## Description

When pasting `defined?(::Ractor)`
(and copying e.g. from https://github.com/ruby/ostruct/pull/29/files)
on ruby-head's irb I get:
```
$ irb
irb(main):001:0> defined?(::Ractor)/home/eregon/prefix/ruby-master/lib/ruby/3.1.0/irb/completion.rb:207:in `retrieve_completion_data': unmatched close parenthesis: /^Ractor)/ (RegexpError)
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/irb/completion.rb:130:in `block in <module:InputCompletor>'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/reline/line_editor.rb:1653:in `call_completion_proc_with_checking_args'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/reline/line_editor.rb:524:in `call_completion_proc_with_checking_args'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/reline.rb:221:in `block in <class:Core>'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/reline/line_editor.rb:569:in `instance_exec'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/reline/line_editor.rb:569:in `call'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/reline/line_editor.rb:604:in `call'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/reline/line_editor.rb:643:in `render_each_dialog'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/reline/line_editor.rb:628:in `block in render_dialog'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/reline/line_editor.rb:627:in `each'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/reline/line_editor.rb:627:in `render_dialog'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/reline/line_editor.rb:491:in `rerender'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/reline.rb:325:in `block (3 levels) in inner_readline'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/reline.rb:323:in `each'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/reline.rb:323:in `block (2 levels) in inner_readline'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/reline.rb:393:in `block in read_io'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/reline.rb:363:in `loop'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/reline.rb:363:in `read_io'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/reline.rb:321:in `block in inner_readline'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/reline.rb:319:in `loop'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/reline.rb:319:in `inner_readline'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/reline.rb:249:in `readmultiline'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/forwardable.rb:238:in `readmultiline'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/forwardable.rb:238:in `readmultiline'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/irb/input-method.rb:388:in `gets'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/irb.rb:538:in `block (2 levels) in eval_input'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/irb.rb:769:in `signal_status'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/irb.rb:537:in `block in eval_input'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/irb/ruby-lex.rb:282:in `lex'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/irb/ruby-lex.rb:251:in `block (2 levels) in each_top_level_statement'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/irb/ruby-lex.rb:248:in `loop'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/irb/ruby-lex.rb:248:in `block in each_top_level_statement'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/irb/ruby-lex.rb:247:in `catch'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/irb/ruby-lex.rb:247:in `each_top_level_statement'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/irb.rb:556:in `eval_input'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/irb.rb:490:in `block in run'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/irb.rb:489:in `catch'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/irb.rb:489:in `run'
	from /home/eregon/prefix/ruby-master/lib/ruby/3.1.0/irb.rb:418:in `start'
	from /home/eregon/prefix/ruby-master/lib/ruby/gems/3.1.0/gems/irb-1.3.8.pre.10/exe/irb:11:in `<top (required)>'
	from /home/eregon/.rubies/ruby-master/bin/irb:25:in `load'
	from /home/eregon/.rubies/ruby-master/bin/irb:25:in `<main>'
```

The new completion seems pretty nifty though :)

## Result of irb_info

```
Ruby version: 3.1.0                            
IRB version: irb 1.3.8.pre.10 (2021-10-03)     
InputMethod: ReidlineInputMethod with Reline 0.2.8.pre.10
.irbrc path: /home/eregon/.irbrc               
RUBY_PLATFORM: x86_64-linux                    
LANG env: en_US.UTF-8
```

## Terminal Emulator

Gnome Terminal, TERM=xterm-256color

## Setting Files

```
$ cat .irbrc 
require 'irb/completion'
require 'irb/ext/save-history'
IRB.conf[:SAVE_HISTORY] = 1000
```

**Comment by aycabta** [comment]
This is fixed by https://github.com/ruby/irb/pull/302.
