### ISSUE TITLE
irb creates $XDG_CONFIG_HOME/irb on start

### ISSUE THREAD

**Issue by piercefaulkner** [ruby/irb#357]
## Description

irb tries to create the `$XDG_CONFIG_HOME/irb` directory on start.

When the path is writeable:
1. Run `XDG_CONFIG_HOME=$HOME/why irb`
2. `~/why/irb` will be created

When the path is inaccessible or the disk is read-only:
1. Run `XDG_CONFIG_HOME=/root irb` as a non-root user
2. An exception occurs

```
/opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/fileutils.rb:243:in `mkdir': Read-only file system @ dir_s_mkdir - /root (Errno::EROFS)
	from /opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/fileutils.rb:243:in `fu_mkdir'
	from /opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/fileutils.rb:221:in `block (2 levels) in mkdir_p'
	from /opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/fileutils.rb:219:in `reverse_each'
	from /opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/fileutils.rb:219:in `block in mkdir_p'
	from /opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/fileutils.rb:211:in `each'
	from /opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/fileutils.rb:211:in `mkdir_p'
	from /opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/irb/init.rb:376:in `rc_file_generators'
	from /opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/irb/init.rb:351:in `rc_file'
	from /opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/irb/init.rb:339:in `rescue in run_config'
	from /opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/irb/init.rb:335:in `run_config'
	from /opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/irb/init.rb:20:in `setup'
	from /opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/irb.rb:412:in `start'
	from /opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
	from /opt/homebrew/opt/ruby/bin/irb:25:in `load'
	from /opt/homebrew/opt/ruby/bin/irb:25:in `<main>'
/opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/fileutils.rb:243:in `mkdir': Read-only file system @ dir_s_mkdir - /root (Errno::EROFS)
	from /opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/fileutils.rb:243:in `fu_mkdir'
	from /opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/fileutils.rb:221:in `block (2 levels) in mkdir_p'
	from /opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/fileutils.rb:219:in `reverse_each'
	from /opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/fileutils.rb:219:in `block in mkdir_p'
	from /opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/fileutils.rb:211:in `each'
	from /opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/fileutils.rb:211:in `mkdir_p'
	from /opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/irb/init.rb:376:in `rc_file_generators'
	from /opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/irb/init.rb:351:in `rc_file'
	from /opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/irb/init.rb:336:in `run_config'
	from /opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/irb/init.rb:20:in `setup'
	from /opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/irb.rb:412:in `start'
	from /opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
	from /opt/homebrew/opt/ruby/bin/irb:25:in `load'
	from /opt/homebrew/opt/ruby/bin/irb:25:in `<main>'
```

## Result of irb_info

```
irb(main):001:0> irb_info
=>
Ruby version: 3.1.1                 
IRB version: irb 1.4.1 (2021-12-25) 
InputMethod: ReidlineInputMethod with Reline 0.3.1
.irbrc path: /Users/aycabta/.irbrc        
RUBY_PLATFORM: arm64-darwin21       
LANG env: en_US.UTF-8               
East Asian Ambiguous Width: 1 
```

## Terminal Emulator

Apple Terminal

## Setting Files

Are you using `~/.irbrc` and `~/.inputrc`?

Only a blank `~/.irbrc`

**Comment by piercefaulkner** [comment]
Has this already been fixed?

https://lists.ruby-lang.org/pipermail/ruby-cvs/2021-March/035601.html
https://github.com/ruby/ruby/commit/e0dd072978

**Comment by piercefaulkner** [comment]
The commit in the comment above fixed the ruby CI setup, not irb or ruby itself.

In order to prevent irb from creating a directory, `$XDG_CONFIG_HOME` needs to be unset before running `irb`.

```sh
unset XDG_CONFIG_HOME
irb
```

https://github.com/ruby/ruby/blob/866a09dd9ea2775a3231c0e9833f3bca48947f30/lib/irb/init.rb#L373-L377
