### ISSUE TITLE
IRB crashes in vi-mode when moving after delete with find

### ISSUE THREAD

**Issue by ilikepi** [ruby/irb#367]
## Description

When using vi-mode editing, I expect to be able to delete text with a find command (e.g. `dfx` to delete text through the next instance of "x") and then enter subsequent movement commands (e.g. `$` to jump to the end of the line) without IRB crashing.

### Steps to reproduce, assuming vi-mode is enabled:

* run `irb`
* enter some text: `irb(main):001:0> irb_info`
* hit escape to enter `command` mode
* enter `0` to jump to the beginning of the line
* enter `df_` to delete the text up to and including the underscore
* enter `$` to jump to the end of the line
* exception is thrown

### Truncated stack trace

```
irb(main):001:0> /Users/person/usr/rubies/ruby-3.1.1/lib/ruby/3.1.0/reline/line_editor.rb:1423:in `run_for_operators': undefined method `>' for nil:NilClass (NoMethodError)

        @vi_arg = @waiting_operator_vi_arg if @waiting_operator_vi_arg > 1
                                                                       ^
	from /Users/person/usr/rubies/ruby-3.1.1/lib/ruby/3.1.0/reline/line_editor.rb:1534:in `process_key'
	from /Users/person/usr/rubies/ruby-3.1.1/lib/ruby/3.1.0/reline/line_editor.rb:1569:in `normal_char'
	from /Users/person/usr/rubies/ruby-3.1.1/lib/ruby/3.1.0/reline/line_editor.rb:1635:in `input_key'
	from /Users/person/usr/rubies/ruby-3.1.1/lib/ruby/3.1.0/reline.rb:329:in `block (3 levels) in inner_readline'
        [...]
```

## Result of irb_info

```
irb(main):001:0> irb_info
=>
Ruby version: 3.1.1
IRB version: irb 1.4.1 (2021-12-25)
InputMethod: ReidlineInputMethod with Reline 0.3.0 and /Users/person/.inputrc
.irbrc path: /Users/person/.irbrc
RUBY_PLATFORM: x86_64-darwin18
LANG env: en_US.UTF-8
East Asian Ambiguous Width: 1
```

## Terminal Emulator

iTerm2 3.3.12, TERM="xterm-256color"

### ~/.inputrc

```
set editing-mode vi
```

**Comment by sshock** [comment]
Can confirm this bug.

Also, I can change `@waiting_operator_vi_arg > 1` to `@waiting_operator_vi_arg.to_i > 1` to fix the crash, but something's still not right because after using `df_` it's still in "delete mode" (e.g., if I press `h` after it deletes the character before).

**Comment by ima1zumi** [comment]
@ilikepi I could not reproduce this bug, is it still occurring in your environment?

**Comment by ima1zumi** [comment]
Probably this is Reline's bug. I will transfer this issue to Reline.
