### ISSUE TITLE
Crashed when using more than 2 chain methods in rails console

### ISSUE THREAD

**Issue by hiro-teaaa** [ruby/irb#460]
## Description

Using irb from `$rails c`, It is crashed when I tried to wrote more than 2 chain methods.

ex) try to execute `[1, 2].map.first`
```

$ irb -v
irb 1.5.0 (2022-11-20)          
$ rails c
Loading development environment (Rails 7.0.4)
irb(main):001:0> [1,2].map.Shutting down background worker
Killing session flushermap!                            
/usr/local/bundle/ruby/3.1.0/gems/dry-logic-1.4.0/lib/dry/logic/predicates.rb:257:in `respond_to?': wrong number of arguments (given 1, expected 2) (ArgumentError)                                                
        from /usr/local/bundle/ruby/3.1.0/gems/irb-1.5.0/lib/irb/completion.rb:364:in `block in retrieve_completion_data'
        from /usr/local/bundle/ruby/3.1.0/gems/irb-1.5.0/lib/irb/completion.rb:362:in `each_object'
        from /usr/local/bundle/ruby/3.1.0/gems/irb-1.5.0/lib/irb/completion.rb:362:in `retrieve_completion_data'
        from /usr/local/bundle/ruby/3.1.0/gems/irb-1.5.0/lib/irb/completion.rb:161:in `block in <module:InputCompletor>'
        from /usr/local/bundle/ruby/3.1.0/gems/reline-0.3.1/lib/reline/line_editor.rb:1681:in `call_completion_proc_with_checking_args'
        from /usr/local/bundle/ruby/3.1.0/gems/reline-0.3.1/lib/reline/line_editor.rb:543:in `call_completion_proc_with_checking_args'
        from /usr/local/bundle/ruby/3.1.0/gems/reline-0.3.1/lib/reline.rb:226:in `block in <class:Core>'
        from /usr/local/bundle/ruby/3.1.0/gems/reline-0.3.1/lib/reline/line_editor.rb:588:in `instance_exec'
        from /usr/local/bundle/ruby/3.1.0/gems/reline-0.3.1/lib/reline/line_editor.rb:588:in `call'
        from /usr/local/bundle/ruby/3.1.0/gems/reline-0.3.1/lib/reline/line_editor.rb:623:in `call'
        from /usr/local/bundle/ruby/3.1.0/gems/reline-0.3.1/lib/reline/line_editor.rb:667:in `render_each_dialog'
        from /usr/local/bundle/ruby/3.1.0/gems/reline-0.3.1/lib/reline/line_editor.rb:651:in `block in render_dialog'
	from /usr/local/bundle/ruby/3.1.0/gems/reline-0.3.1/lib/reline/line_editor.rb:650:in `each'
	from /usr/local/bundle/ruby/3.1.0/gems/reline-0.3.1/lib/reline/line_editor.rb:650:in `render_dialog'
	from /usr/local/bundle/ruby/3.1.0/gems/reline-0.3.1/lib/reline/line_editor.rb:510:in `rerender'
	from /usr/local/bundle/ruby/3.1.0/gems/reline-0.3.1/lib/reline.rb:330:in `block (3 levels) in inner_readline'
	from /usr/local/bundle/ruby/3.1.0/gems/reline-0.3.1/lib/reline.rb:328:in `each'
	from /usr/local/bundle/ruby/3.1.0/gems/reline-0.3.1/lib/reline.rb:328:in `block (2 levels) in inner_readline'
	from /usr/local/bundle/ruby/3.1.0/gems/reline-0.3.1/lib/reline.rb:403:in `block in read_io'
	from /usr/local/bundle/ruby/3.1.0/gems/reline-0.3.1/lib/reline.rb:373:in `loop'
	from /usr/local/bundle/ruby/3.1.0/gems/reline-0.3.1/lib/reline.rb:373:in `read_io'
	from /usr/local/bundle/ruby/3.1.0/gems/reline-0.3.1/lib/reline.rb:326:in `block in inner_readline'
	from /usr/local/bundle/ruby/3.1.0/gems/reline-0.3.1/lib/reline.rb:324:in `loop'
	from /usr/local/bundle/ruby/3.1.0/gems/reline-0.3.1/lib/reline.rb:324:in `inner_readline'
	from /usr/local/bundle/ruby/3.1.0/gems/reline-0.3.1/lib/reline.rb:254:in `readmultiline'
	from /usr/local/lib/ruby/3.1.0/forwardable.rb:238:in `readmultiline'
	from /usr/local/lib/ruby/3.1.0/forwardable.rb:238:in `readmultiline'
	from /usr/local/bundle/ruby/3.1.0/gems/irb-1.5.0/lib/irb/input-method.rb:422:in `gets'
	from /usr/local/bundle/ruby/3.1.0/gems/irb-1.5.0/lib/irb.rb:550:in `block (2 levels) in eval_input'
	from /usr/local/bundle/ruby/3.1.0/gems/irb-1.5.0/lib/irb.rb:779:in `signal_status'
	from /usr/local/bundle/ruby/3.1.0/gems/irb-1.5.0/lib/irb.rb:549:in `block in eval_input'
	from /usr/local/bundle/ruby/3.1.0/gems/irb-1.5.0/lib/irb/ruby-lex.rb:283:in `lex'
	from /usr/local/bundle/ruby/3.1.0/gems/irb-1.5.0/lib/irb/ruby-lex.rb:252:in `block (2 levels) in each_top_level_statement'
	from /usr/local/bundle/ruby/3.1.0/gems/irb-1.5.0/lib/irb/ruby-lex.rb:249:in `loop'
	from /usr/local/bundle/ruby/3.1.0/gems/irb-1.5.0/lib/irb/ruby-lex.rb:249:in `block in each_top_level_statement'
	from /usr/local/bundle/ruby/3.1.0/gems/irb-1.5.0/lib/irb/ruby-lex.rb:248:in `catch'
	from /usr/local/bundle/ruby/3.1.0/gems/irb-1.5.0/lib/irb/ruby-lex.rb:248:in `each_top_level_statement'
	from /usr/local/bundle/ruby/3.1.0/gems/irb-1.5.0/lib/irb.rb:568:in `eval_input'
	from /usr/local/bundle/ruby/3.1.0/gems/irb-1.5.0/lib/irb.rb:502:in `block in run'
	from /usr/local/bundle/ruby/3.1.0/gems/irb-1.5.0/lib/irb.rb:501:in `catch'
	from /usr/local/bundle/ruby/3.1.0/gems/irb-1.5.0/lib/irb.rb:501:in `run'
	from /usr/local/bundle/ruby/3.1.0/gems/irb-1.5.0/lib/irb.rb:419:in `start'
	from /usr/local/bundle/ruby/3.1.0/gems/railties-7.0.4/lib/rails/commands/console/console_command.rb:70:in `start'
	from /usr/local/bundle/ruby/3.1.0/gems/railties-7.0.4/lib/rails/commands/console/console_command.rb:19:in `start'
	from /usr/local/bundle/ruby/3.1.0/gems/railties-7.0.4/lib/rails/commands/console/console_command.rb:102:in `perform'
	from /usr/local/bundle/ruby/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/ruby/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/ruby/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/ruby/3.1.0/gems/railties-7.0.4/lib/rails/command/base.rb:87:in `perform'
	from /usr/local/bundle/ruby/3.1.0/gems/railties-7.0.4/lib/rails/command.rb:48:in `invoke'
	from /usr/local/bundle/ruby/3.1.0/gems/railties-7.0.4/lib/rails/commands.rb:18:in `<main>'
	from /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.14.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /usr/local/bundle/ruby/3.1.0/gems/bootsnap-1.14.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from bin/rails:6:in `<main>'
```
It's happened when I typing out the second `.` .

But not happened when ` irb version is 1.4.2`
```
$ irb -v
irb 1.4.2 (2022-10-03)
$ rails c
Loading development environment (Rails 7.0.4)
irb(main):003:0> [1, 2].map.first
=> 1
```

## Result of irb_info

Please paste the result of `irb_info` command in IRB.

```
irb(main):001:0> irb_info
=> 
Ruby version: 3.1.2                            
IRB version: irb 1.5.0 (2022-11-20)            
InputMethod: RelineInputMethod with Reline 0.3.1
RUBY_PLATFORM: aarch64-linux                   
LANG env: C.UTF-8                              
East Asian Ambiguous Width: 1    
```

## Terminal Emulator

What's your terminal emulator?
=> `zsh 5.8.1 (x86_64-apple-darwin21.0)`

## Setting Files

Are you using `~/.irbrc` and `~/.inputrc`?
=> No

**Comment by st0012** [comment]
It should be fixed by upgrading dry-logic: https://github.com/dry-rb/dry-logic/issues/104

**Comment by hiro-teaaa** [comment]
@st0012 
Its fixed. I had missed the dry-logic issue.
