### ISSUE TITLE
How do I get the last exception that occurred?

### ISSUE THREAD

**Issue by janko** [ruby/irb#485]
## Description

When an exception happens in my IRB session, I often want to retrieve the last raised exception. In Pry, I could do this via `_ex_`. In IRB I tried `$!`, but it returned `nil`. Is there a way to obtain the exception?

## Result of irb_info

```
irb(main):001:0> irb_info
=>
Ruby version: 3.2.0
IRB version: irb 1.6.2 (2022-12-13)
InputMethod: RelineInputMethod with Reline 0.3.2
.irbrc path: /Users/janko/.irbrc
RUBY_PLATFORM: arm64-darwin22
East Asian Ambiguous Width: 1
```

## Terminal Emulator

I'm using Terminal.app with tmux.

**Comment by st0012** [comment]
Currently, if an input causes an exception, you can retrieve it like retrieving the latest returned value with `_`. For example,

```
irb(main):001:0> 1/0
(irb):1:in `/': divided by 0 (ZeroDivisionError)
        from (irb):1:in `<main>'
        from /Users/st0012/projects/irb/exe/irb:11:in `<top (required)>'
        from /Users/st0012/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/bin/irb:25:in `load'
        from /Users/st0012/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/bin/irb:25:in `<top (required)>'
        from /Users/st0012/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.2.32/lib/bundler/cli/exec.rb:58:in `load'
        from /Users/st0012/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.2.32/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /Users/st0012/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.2.32/lib/bundler/cli/exec.rb:23:in `run'
        from /Users/st0012/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.2.32/lib/bundler/cli.rb:478:in `exec'
        from /Users/st0012/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /Users/st0012/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/st0012/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /Users/st0012/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.2.32/lib/bundler/cli.rb:31:in `dispatch'
        from /Users/st0012/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /Users/st0012/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.2.32/lib/bundler/cli.rb:25:in `start'
        from /Users/st0012/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.2.32/exe/bundle:49:in `block in <top (required)>'
        from /Users/st0012/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.2.32/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
        ... 3 levels...
irb(main):002:0> puts _.inspect
#<ZeroDivisionError: divided by 0>
=> nil
```

It's not exactly the same as `_ex_` because it'd be replaced by the next input's return value. But I imagine `_ex_` is also usually called right after the exception occurred?

**Comment by janko** [comment]
Thanks, it didn't occur to me to try `_`, that works for me! 🙂
