### ISSUE TITLE
Lazy load of commands doesn't work on frozen objects

### ISSUE THREAD

**Issue by k0kubun** [ruby/irb#497]
### Input script
```rb
# /tmp/a.rb
klass = Class.new do
  def binding_irb
    freeze
    binding.irb
  end
end
klass.new.binding_irb
```

### Current behavior
IRB fails to lazily load a command on a frozen object, e.g. `ls`.

```rb
$ ruby -v /tmp/a.rb
ruby 3.2.0 (2022-12-25 revision a528908271) [x86_64-linux]

From: /tmp/a.rb @ line 4 :

    1: klass = Class.new do
    2:   def binding_irb
    3:     freeze
 => 4:     binding.irb
    5:   end
    6: end
    7: klass.new.binding_irb

irb(#<#<Class:0x00007ff941d91060>:0x00007ff944e86ff8>):001:0> ls
/opt/rubies/3.2.0/lib/ruby/3.2.0/delegate.rb:89:in `require_relative': cannot load such file -- /opt/rubies/3.2.0/lib/ruby/3.2.0/cmd/ls (LoadError)
        from /opt/rubies/3.2.0/lib/ruby/3.2.0/delegate.rb:89:in `bind_call'
        from /opt/rubies/3.2.0/lib/ruby/3.2.0/delegate.rb:89:in `method_missing'
        from /tmp/a.rb:1:in `binding_irb'
        from <internal:prelude>:5:in `irb'
        from /tmp/a.rb:4:in `binding_irb'
        from /tmp/a.rb:7:in `<main>'
```

### Expected behavior

IRB successfully loads `ls` command lazily on a frozen object.

```rb
$ ruby -v /tmp/a.rb
ruby 3.2.0 (2022-12-25 revision a528908271) [x86_64-linux]

From: /tmp/a.rb @ line 4 :

    1: klass = Class.new do
    2:   def binding_irb
    3:     freeze
 => 4:     binding.irb
    5:   end
    6: end
    7: klass.new.binding_irb

irb(#<#<Class:0x00007f3318fb1060>:0x00007f331c0a7020>):001:0> ls
#<Class:0x00007f3318fb1060>#methods: binding_irb
IRB::ExtendCommandBundle#methods:
  install_alias_method  irb                 irb_backtrace                  irb_break      irb_catch        irb_change_workspace
  irb_context           irb_continue        irb_current_working_workspace  irb_debug      irb_debug_info   irb_delete
  irb_edit              irb_exit            irb_fg                         irb_finish     irb_help         irb_info
  irb_jobs              irb_kill            irb_load                       irb_ls         irb_measure      irb_next
  irb_pop_workspace     irb_push_workspace  irb_require                    irb_show_cmds  irb_show_source  irb_source
  irb_step              irb_whereami        irb_workspaces
#<Class:0x00007f3318fb1060>.methods:
  backtrace                  bindings                     bt                  cb               chws                         conf
  context                    continue                     cws                 cwws             debug                        delete
  edit                       exit                         fg                  finish           help                         info
  irb_bindings               irb_cb                       irb_change_binding  irb_chws         irb_current_working_binding  irb_cwb
  irb_cws                    irb_cwws                     irb_ls_             irb_pop_binding  irb_popb                     irb_popws
  irb_print_working_binding  irb_print_working_workspace  irb_push_binding    irb_pushb        irb_pushws                   irb_pwb
  irb_pwws                   irb_quit                     jobs                kill             ls                           measure
  popb                       popws                        pushb               pushws           pwws                         quit
  show_cmds                  show_doc                     show_source         source           step                         whereami
  workspaces
locals: _
=> nil
```

## Result of irb_info

```
irb(main):001:0> irb_info
=>
Ruby version: 3.2.0
IRB version: irb 1.6.2 (2022-12-13)
InputMethod: RelineInputMethod with Reline 0.3.2
RUBY_PLATFORM: x86_64-linux
LANG env: en_US.UTF-8
East Asian Ambiguous Width: 1
```

## Terminal Emulator

gnome-terminal

## Setting Files

I reproduced the issue with `~/.irbrc` removed.

**Comment by st0012** [comment]
Thanks for reporting it. I've opened #498 to address the issue 🙂
