### ISSUE TITLE
How to see backtrace?

### ISSUE THREAD

**Issue by hakunin** [ruby/irb#525]
## Description

When I run code inside of `rails c` that causes an exception, I see the error gets printed out, but not the backtrace.

For example:

```
>> Dataset.find(10).trigger(:enqueue_websites)
/home/michal/.rvm/gems/ruby-3.1.3/gems/activerecord-7.0.4/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `exec_params': PG::NotNullViolation: ERROR:  null value in column "string_id" of relation "rows" violates not-null constraint (ActiveRecord::NotNullViolation)
DETAIL:  Failing row contains (1355467, null, {"url": "http//:www.multiverso.net", "scope": "gid://scraping/Da..., 29, 2023-02-26 11:06:39.681892, 2023-02-26 11:06:39.681892, null, {}, null, f).
/home/michal/.rvm/gems/ruby-3.1.3/gems/activerecord-7.0.4/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `exec_params': ERROR:  null value in column "string_id" of relation "rows" violates not-null constraint (PG::NotNullViolation)
DETAIL:  Failing row contains (1355467, null, {"url": "http//:www.multiverso.net", "scope": "gid://scraping/Da..., 29, 2023-02-26 11:06:39.681892, 2023-02-26 11:06:39.681892, null, {}, null, f).
>>
```

So I guess there is a way to *see* the backtrace somehow, but didn't find it anywhere.
Ideally I want to see it every time and use the rails cleaner. I've tried configuring irb to do that but with no luck.

## Result of irb_info

> Please paste the result of `irb_info` command in IRB.

```
=> Ruby version: 3.1.3
IRB version: irb 1.6.2 (2022-12-13)
InputMethod: RelineInputMethod with Reline 0.3.1
.irbrc path: /home/michal/.rvm/rubies/ruby-3.1.3/.irbrc
RUBY_PLATFORM: x86_64-linux
LANG env: en_US.UTF-8
East Asian Ambiguous Width: 1
```

## Terminal Emulator

Tmux running under Guake.

## Setting Files

> Are you using `~/.irbrc` and `~/.inputrc`?

Yes, `~/.irbrc`.

```
IRB.conf[:BACK_TRACE_LIMIT]= 20

# autocomplete colors
IRB.conf[:DIALOG_DEFAULT_BG_COLOR] = 40
IRB.conf[:DIALOG_POINTER_BG_COLOR] = 47

# avoid printing result on the same line, overriding the content of the line

$interactive = true

# gem 'reline',  github: 'pocari/reline',
#   branch: 'support-for-changing-the-background-color-of-dialogs'
if Reline.respond_to? :dialog_default_bg_color
  Reline.dialog_default_bg_color = 40
  Reline.dialog_pointer_bg_color = 47
  Reline.dialog_pointer_fg_color = 30
  Reline.dialog_pointer_bg_color = 45
end

# from https://gist.github.com/xeger/ceca893a4490fd87d3d4c69d8a481c30
begin
  c = IRB::Color
  token_seq_exprs = IRB::Color::const_get(:TOKEN_SEQ_EXPRS)

  one_dark = {
    on_comment: [c::CLEAR], # needs italics
    on_const:  [c::YELLOW, c::BOLD],
    on_label: [c::YELLOW],
    on_kw:  [c::MAGENTA],
    on_tstring_beg: [c::GREEN, c::BOLD],
    on_tstring_content: [c::GREEN],
    on_tstring_end: [c::GREEN, c::BOLD],
  }

  one_dark.each_pair do |token, theme_colors|
    if stdconfig = token_seq_exprs[token]
      stdconfig[0] = theme_colors
    end
  end
rescue
  puts "Error setting colors"
end

FANCY_OPTIONS = {
  :rocket_mode     => false,       # activate or deactivate #=> rocket
  :rocket_prompt   => '# => ',     # prompt to use for the rocket
  :result_prompt   => '=> ',      # prompt to use for normal output
  :unicode_display_width => true, # set to false if you don't want to check for proper
                                  # string width for better performance
  colorize: {                  # colors hash. Set to nil to deactivate colors
    :rocket_prompt => [:gray],
    :result_prompt => [:blue],
    :input_prompt  => nil,
    :irb_errors    => [:red, :clean],
    :stderr        => [:red, :bright],
    :stdout        => nil,
    :input         => nil,
   },
}

require 'irbtools/configure'

Irbtools.replace_library_callback :fancy_irb do
  FancyIrb.start(FANCY_OPTIONS)
end

require 'irbtools'

old_logger = ActiveRecord::Base.logger
ActiveRecord::Base.logger = nil
```

**Comment by ima1zumi** [comment]
Could you show us the minimum sample code to reproduce this problem?

**Comment by hakunin** [comment]
So I assume the backtrace should come up normally.
I've setup a fresh app I get the exception backtrace it seems so I'll have to experiment with this.

Is there a way to customize the exception handler so I can debug it better?

**Comment by hakunin** [comment]
I think it has to do with a specific exception type or exception being thrown from within a gem.

For example if I save a record that causes a validation error I get this:

```
rows.find_or_create_by!(key: nil) # <-- key mut be present
```

I guet this:

```
/home/michal/.rvm/gems/ruby-3.1.3/gems/activerecord-7.0.4/lib/active_record/connection_adapters/postgresql_adapter.rb:837:in `prepare': PG::UndefinedColumn: ERROR:  column rows.key does not exist (ActiveRecord::StatementInvalid)
LINE 1: ...ws".* FROM "rows" WHERE "rows"."node_id" = $1 AND "rows"."ke...
                                                             ^
/home/michal/.rvm/gems/ruby-3.1.3/gems/activerecord-7.0.4/lib/active_record/connection_adapters/postgresql_adapter.rb:837:in `prepare': ERROR:  column rows.key does not exist (PG::UndefinedColumn)
LINE 1: ...ws".* FROM "rows" WHERE "rows"."node_id" = $1 AND "rows"."ke...
                                                             ^
>>
```

**Comment by hakunin** [comment]
So I set out to reproduce this on a fresh app and it happens too.
I removed my `~/.irbrc` contents and error is the same:

Code:
```
class TestRow < ApplicationRecord
  def self.test_create
    create!(blah: nil)
  end
end
```

Result:
```
3.1.3 :001 > TestRow.test_create
/home/michal/.rvm/gems/ruby-3.1.3/gems/activerecord-7.0.4.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:387:in `table_structure': Could not find table 'test_rows' (ActiveRecord::StatementInvalid)
```

Here I should have gotten backtrace with a line that caused the exception from the model file.

**Comment by hakunin** [comment]
I've identified where the lines get removed:

https://github.com/ruby/irb/blob/97dae166ae51b87fe611d1dd81e80c170b504ce7/lib/irb.rb#L671

I modified the code:

```
          ap [:LINES_BEFORE, lines]

          lines = lines.map { |l| @context.workspace.filter_backtrace(l) }.compact

          ap [:LINES_AFTER, lines]
```

And the output is:

```
[
  :LINES_BEFORE,
  [
    "\tfrom /home/michal/.rvm/gems/ruby-3.1.3/gems/activerecord-7.0.4/lib/active_record/connection_adapters/postgresql_adapter.rb:837:in `block in prepare_statement'",
    "\tfrom /home/michal/.rvm/gems/ruby-3.1.3/gems/activesupport-7.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'",
    "\tfrom /home/michal/.rvm/gems/ruby-3.1.3/gems/activesupport-7.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'",
    "\tfrom /home/michal/.rvm/gems/ruby-3.1.3/gems/activesupport-7.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'",
    "\tfrom /home/michal/.rvm/gems/ruby-3.1.3/gems/activesupport-7.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'",
    "\tfrom /home/michal/.rvm/gems/ruby-3.1.3/gems/activerecord-7.0.4/lib/active_record/connection_adapters/postgresql_adapter.rb:832:in `prepare_statement'",
    "\tfrom /home/michal/.rvm/gems/ruby-3.1.3/gems/activerecord-7.0.4/lib/active_record/connection_adapters/postgresql_adapter.rb:778:in `exec_cache'",
    "\tfrom /home/michal/.rvm/gems/ruby-3.1.3/gems/activerecord-7.0.4/lib/active_record/connection_adapters/postgresql_adapter.rb:747:in `execute_and_clear'",
    "\tfrom /home/michal/.rvm/gems/ruby-3.1.3/gems/activerecord-7.0.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:54:in `exec_query'",
    "\tfrom /home/michal/.rvm/gems/ruby-3.1.3/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/database_statements.rb:560:in `select'",
    [10] .. [61],
    "\tfrom /home/michal/.rvm/gems/ruby-3.1.3/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'",
    "\tfrom /home/michal/.rvm/gems/ruby-3.1.3/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'",
    "\tfrom /home/michal/.rvm/gems/ruby-3.1.3/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'",
    "\tfrom /home/michal/.rvm/gems/ruby-3.1.3/gems/railties-7.0.4/lib/rails/command/base.rb:87:in `perform'",
    "\tfrom /home/michal/.rvm/gems/ruby-3.1.3/gems/railties-7.0.4/lib/rails/command.rb:48:in `invoke'",
    "\tfrom /home/michal/.rvm/gems/ruby-3.1.3/gems/railties-7.0.4/lib/rails/commands.rb:18:in `<main>'",
    "\tfrom /home/michal/.rvm/gems/ruby-3.1.3/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'",
    "\tfrom /home/michal/.rvm/gems/ruby-3.1.3/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'",
    "\tfrom bin/rails:4:in `<main>'"
  ]
]
[
  :LINES_AFTER,
  []
]
```

And the cleaner being used is from Rails:
```
p @context.workspace.method(:filter_backtrace)

#<Method: IRB::WorkSpace(Rails::Console::BacktraceCleaner)#filter_backtrace(bt) /home/michal/.rvm/gems/ruby-3.1.3/gems/railties-7.0.4/lib/rails/commands/console/console_command.rb:11>
```

So it's the rails code making the backtrace disappear. I think I can figure it out from here.

**Comment by hakunin** [comment]
Hmm I'm not sure what this super does here:
```
module Rails
  class Console
    module BacktraceCleaner
      def filter_backtrace(bt)
        if result = super # <-- here
          Rails.backtrace_cleaner.filter([result]).first # <-- only the first?
        end
      end
    end
```

It may have to do with IRB after all, not sure.

I've updated from Rails `7.0.4` to `7.0.4.2` and the bug persists.

For now I'm sticking with my workaround:

```
class IRB::Irb
  def handle_exception(e)
    puts "\n#{e.message}"
    puts Rails.backtrace_cleaner.clean(e.backtrace)
  end
end
```

**Comment by ima1zumi** [comment]
It seems to be removing backtraces if it doesn't match `APP_DIRS_PATTERN` by Rails.
Maybe if you change `Rails::BacktraceCleaner::APP_DIRS_PATTERN` you can control what is displayed.

https://github.com/rails/rails/blob/629a32148c8959fb37314f1a47c075130f4b3a93/railties/lib/rails/backtrace_cleaner.rb#L24

**Comment by ima1zumi** [comment]
And this does not seem to be IRB problem.
If you have any questions, I would appreciate it if you could ask Rails.

**Comment by hakunin** [comment]
> It seems to be removing backtraces if it doesn't match `APP_DIRS_PATTERN` by Rails. Maybe if you change `Rails::BacktraceCleaner::APP_DIRS_PATTERN` you can control what is displayed.
> 
> https://github.com/rails/rails/blob/629a32148c8959fb37314f1a47c075130f4b3a93/railties/lib/rails/backtrace_cleaner.rb#L24

Could it be a combinatiof IRB doing cleaning one line at a time and Rails doing it based on the whole trace?
For example, all non-application trace lines are removed if it is raised from the app itself. (which in this case it is)
It would be cause by Rails, but also a design fault in IRB itself, since it does it one line at a time.

**Comment by mame** [comment]
@hakunin 

> For now I'm sticking with my workaround by putting this into my `~/.irbrc`:

Could you show us how the backtrace is shown with this workaround?

> It would be cause by Rails, but also a design fault in IRB itself, since it does it one line at a time.

From looking at the code, I think `Rails.backtrace_cleaner.clean` is also just processing one line at a time.

https://github.com/rails/rails/blob/629a32148c8959fb37314f1a47c075130f4b3a93/activesupport/lib/active_support/backtrace_cleaner.rb#L115-L118

So I'm curious what your workaround will change.

**Comment by elfham** [comment]
Can you find the line from `_.backtrace` ?

**Comment by hakunin** [comment]
Sorry I didn't want to spend more time debugging this and ended up switching back to Pry, because of another bug wihth IRB / IRB Tools, or some combination of something, where doing `binding.irb` causes the history of commands to clear way too many commands and I ended up typing everything again.
