### ISSUE TITLE
⌘+Backspace cause Encoding::UndefinedConversionError

### ISSUE THREAD

**Issue by Beyarz** [ruby/irb#62]
Version:
`irb 1.2.1 (2019-12-24)`

Crash log:
```
$ irb                                                    ‹ruby-2.7.0›
2.7.0 :001 > Traceback (most recent call last):
        35: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/bin/irb:23:in `<main>'
        34: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/bin/irb:23:in `load'
        33: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/irb-1.2.1/exe/irb:11:in `<top (required)>'
        32: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb.rb:398:in `start'
        31: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb.rb:469:in `run'
        30: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb.rb:469:in `catch'
        29: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb.rb:470:in `block in run'
        28: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb.rb:535:in `eval_input'
        27: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb/ruby-lex.rb:134:in `each_top_level_statement'
        26: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb/ruby-lex.rb:134:in `catch'
        25: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb/ruby-lex.rb:135:in `block in each_top_level_statement'
        24: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb/ruby-lex.rb:135:in `loop'
        23: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb/ruby-lex.rb:138:in `block (2 levels) in each_top_level_statement'
        22: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb/ruby-lex.rb:166:in `lex'
        21: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb.rb:516:in `block in eval_input'
        20: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb.rb:693:in `signal_status'
        19: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb.rb:517:in `block (2 levels) in eval_input'
        18: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb/input-method.rb:258:in `gets'
        17: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/forwardable.rb:235:in `readmultiline'
        16: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/forwardable.rb:235:in `readmultiline'
        15: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/reline.rb:170:in `readmultiline'
        14: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/reline.rb:232:in `inner_readline'
        13: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/reline.rb:232:in `loop'
        12: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/reline.rb:233:in `block in inner_readline'
        11: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/reline.rb:262:in `read_io'
        10: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/reline.rb:262:in `loop'
         9: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/reline.rb:286:in `block in read_io'
         8: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/reline.rb:234:in `block (2 levels) in inner_readline'
         7: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/reline.rb:234:in `each'
         6: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/reline.rb:235:in `block (3 levels) in inner_readline'
         5: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/reline/line_editor.rb:829:in `input_key'
         4: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/reline/line_editor.rb:787:in `normal_char'
         3: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/reline/line_editor.rb:758:in `process_key'
         2: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/reline/line_editor.rb:1109:in `ed_insert'
         1: from /Users/beyarz/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/reline/unicode.rb:70:in `get_mbchar_width'
/Users/beyarz/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/reline/unicode.rb:70:in `encode': "\\xF7" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
```

**Comment by nobu** [comment]
What terminal emulator are you using?
I can't reproduce it with the standard Terminal.app on macOS Catalina.

**Comment by Beyarz** [comment]
> What terminal emulator are you using?
> I can't reproduce it with the standard Terminal.app on macOS Catalina.
[hyper](https://hyper.is)

**Comment by nobu** [comment]
I could reproduce it with ruby 2.7.0 on Hyper.
It seems fixed already in the master.
