### ISSUE TITLE
Multi-line multibyte regular expression raises exception

### ISSUE THREAD

**Issue by elfham** [ruby/irb#627]
## Description

An exception occurs when attempting to enter a multi-line multi-byte regular expression.

#### Scenario:

Type `/`, <kbd>Enter</kbd>, `あ`, <kbd>Enter</kbd>, `/`, <kbd>Enter</kbd>.

#### Expected:

```
% irb
irb(main):001:0/ /
irb(main):002:0/ あ
irb(main):003:0> /
=>
/
\u3042
/
irb(main):004:0>
```

#### Actual:

Type `/`, <kbd>Enter</kbd>, `あ`, <kbd>Enter</kbd>, then,

```
% irb
irb(main):001:0/ /
irb(main):002:0/ あ/var/work/src/irb_ruby/lib/irb/ruby-lex.rb:97:in `match?': invalid byte sequence in UTF-8 (ArgumentError)
        from /var/work/src/irb_ruby/lib/irb/ruby-lex.rb:97:in `block in configure_io'
        from /var/work/lib/ruby/reline/line_editor.rb:1648:in `process_auto_indent'
        from /var/work/lib/ruby/reline/line_editor.rb:1603:in `input_key'
        from /var/work/lib/ruby/reline.rb:349:in `block (3 levels) in inner_readline'
        from /var/work/lib/ruby/reline.rb:348:in `each'
        from /var/work/lib/ruby/reline.rb:348:in `block (2 levels) in inner_readline'
        from /var/work/lib/ruby/reline.rb:423:in `block in read_io'
        from /var/work/lib/ruby/reline.rb:393:in `loop'
        from /var/work/lib/ruby/reline.rb:393:in `read_io'
        from /var/work/lib/ruby/reline.rb:346:in `block in inner_readline'
        from /var/work/lib/ruby/reline.rb:344:in `loop'
        from /var/work/lib/ruby/reline.rb:344:in `inner_readline'
        from /var/work/lib/ruby/reline.rb:273:in `block in readmultiline'
        from /var/work/lib/ruby/reline/ansi.rb:149:in `block in with_raw_input'
        from /var/work/lib/ruby/reline/ansi.rb:149:in `raw'
        from /var/work/lib/ruby/reline/ansi.rb:149:in `with_raw_input'
        from /var/work/lib/ruby/reline.rb:269:in `readmultiline'
        from /usr/local/lib/ruby/3.1/forwardable.rb:238:in `readmultiline'
        from /usr/local/lib/ruby/3.1/forwardable.rb:238:in `readmultiline'
        from /var/work/src/irb_ruby/lib/irb/input-method.rb:418:in `gets'
        from /var/work/src/irb_ruby/lib/irb.rb:540:in `block (2 levels) in eval_input'
        from /var/work/src/irb_ruby/lib/irb.rb:764:in `signal_status'
        from /var/work/src/irb_ruby/lib/irb.rb:539:in `block in eval_input'
        from /var/work/src/irb_ruby/lib/irb/ruby-lex.rb:220:in `readmultiline'
        from /var/work/src/irb_ruby/lib/irb/ruby-lex.rb:246:in `block in each_top_level_statement'
        from /var/work/src/irb_ruby/lib/irb/ruby-lex.rb:245:in `loop'
        from /var/work/src/irb_ruby/lib/irb/ruby-lex.rb:245:in `each_top_level_statement'
        from /var/work/src/irb_ruby/lib/irb.rb:558:in `eval_input'
        from /var/work/src/irb_ruby/lib/irb.rb:494:in `block in run'
        from /var/work/src/irb_ruby/lib/irb.rb:493:in `catch'
        from /var/work/src/irb_ruby/lib/irb.rb:493:in `run'
        from /var/work/src/irb_ruby/lib/irb.rb:416:in `start'
        from /var/work/src/irb/exe/irb:9:in `<main>'
%
```

## Result of irb_info

```
irb(main):001:0> irb_info
Ruby version: 3.1.4
IRB version: irb 1.7.1 (2023-07-01)
InputMethod: RelineInputMethod with Reline 0.3.5
RUBY_PLATFORM: amd64-freebsd13
LANG env: ja_JP.UTF-8
East Asian Ambiguous Width: 2
=> nil
```

## Terminal Emulator

PuTTYrv 0.78-ranvis2 (CJK)

## Setting Files

No ~/.irbrc or ~/.inputrc.

**Comment by tompng** [comment]
This is fixed in https://github.com/ruby/reline/pull/562 and Reline 0.3.6 is released.
