### ISSUE TITLE
IRB 2.7.0 crush: undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by woarewe** [ruby/irb#64]
Hi, everyone!

I've found some unexpected behavior of IRB 2.7. If you enter the [following code](https://gist.github.com/woarewe/f7a4f18a4fee7e97e654ca6e11e55e2d) to the REPL you will get next backtrace:

```ruby
2.7.0 :001 > class Symbol
2.7.0 :002 >   def to_proc(*args)
2.7.0 :003 >     proc {}
2.7.0 :004 >   end
2.7.0 :005 > end
 => :to_proc
Traceback (most recent call last):
	29: from /Users/woarewe/.rvm/rubies/ruby-2.7.0/bin/irb:23:in `<main>'
	28: from /Users/woarewe/.rvm/rubies/ruby-2.7.0/bin/irb:23:in `load'
	27: from /Users/woarewe/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/irb-1.2.1/exe/irb:11:in `<top (required)>'
	26: from /Users/woarewe/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb.rb:398:in `start'
	25: from /Users/woarewe/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb.rb:469:in `run'
	24: from /Users/woarewe/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb.rb:469:in `catch'
	23: from /Users/woarewe/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb.rb:470:in `block in run'
	22: from /Users/woarewe/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb.rb:535:in `eval_input'
	21: from /Users/woarewe/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb/ruby-lex.rb:134:in `each_top_level_statement'
	20: from /Users/woarewe/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb/ruby-lex.rb:134:in `catch'
	19: from /Users/woarewe/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb/ruby-lex.rb:135:in `block in each_top_level_statement'
	18: from /Users/woarewe/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb/ruby-lex.rb:135:in `loop'
	17: from /Users/woarewe/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb/ruby-lex.rb:138:in `block (2 levels) in each_top_level_statement'
	16: from /Users/woarewe/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb/ruby-lex.rb:166:in `lex'
	15: from /Users/woarewe/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb.rb:516:in `block in eval_input'
	14: from /Users/woarewe/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb.rb:693:in `signal_status'
	13: from /Users/woarewe/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb.rb:517:in `block (2 levels) in eval_input'
	12: from /Users/woarewe/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb/input-method.rb:258:in `gets'
	11: from /Users/woarewe/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/forwardable.rb:235:in `readmultiline'
	10: from /Users/woarewe/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/forwardable.rb:235:in `readmultiline'
	 9: from /Users/woarewe/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/reline.rb:170:in `readmultiline'
	 8: from /Users/woarewe/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/reline.rb:221:in `inner_readline'
	 7: from /Users/woarewe/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/reline/line_editor.rb:330:in `rerender'
	 6: from /Users/woarewe/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/reline/line_editor.rb:77:in `check_multiline_prompt'
	 5: from /Users/woarewe/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb/ruby-lex.rb:50:in `block in set_input'
	 4: from /Users/woarewe/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb/ruby-lex.rb:50:in `each_index'
	 3: from /Users/woarewe/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb/ruby-lex.rb:52:in `block (2 levels) in set_input'
	 2: from /Users/woarewe/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb/ruby-lex.rb:110:in `check_state'
	 1: from /Users/woarewe/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb/ruby-lex.rb:456:in `process_literal_type'
/Users/woarewe/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/irb/ruby-lex.rb:424:in `check_string_literal': undefined method `[]' for nil:NilClass (NoMethodError)
```

Thanks for your attention.

**Comment by nobu** [comment]
You overrides `Symbol#to_proc` and breaks `Ripper.lex` (and many other thins).

**Comment by woarewe** [comment]
I got it, thanks.
