### ISSUE TITLE
Pasting this program causes IRB to crash

### ISSUE THREAD

**Issue by schneems** [ruby/irb#74]
## Description

Paste this into IRB:

```
class Foo

  def foo?
  end
end

f = Foo.new

require 'benchmark/ips'

Benchmark.ips do |x|
  x.report("respond_to") {
    f.respond_to?(:foo?)
  }
  x.report("is_a?") { 
    f.is_a?(Foo)
  }
  x.compare!
end
```

It should not crash, but it does:

```
$ irb
irb(main):001:1* class Foo
irb(main):002:1*
irb(main):003:2*   def foo?
irb(main):004:1*   end
irb(main):005:0> end
=> :foo?
irb(main):006:0>
irb(main):007:0> f = Foo.new
irb(main):008:0>
irb(main):009:0> require 'benchmark/ips'
=> true
irb(main):010:0>
irb(main):011:1* Benchmark.ips do |x|
irb(main):012:2*   x.report("respond_to") {
irb(main):013:2*     f.respond_to?(:foo?)
irb(main):014:1*   }
irb(main):015:2* x.report("is_a?") {
irb(main):016:2*   f.is_a?(Foo)
irb(main):017:1* }
irb(main):018:1*   x.compare!Traceback (most recent call last):
	32: from /Users/rschneeman/.rubies/ruby-2.7.0/bin/irb:23:in `<main>'
	31: from /Users/rschneeman/.rubies/ruby-2.7.0/bin/irb:23:in `load'
	30: from /Users/rschneeman/.gem/ruby/2.7.0/gems/irb-1.2.1/exe/irb:11:in `<top (required)>'
	29: from /Users/rschneeman/.gem/ruby/2.7.0/gems/irb-1.2.1/lib/irb.rb:398:in `start'
	28: from /Users/rschneeman/.gem/ruby/2.7.0/gems/irb-1.2.1/lib/irb.rb:469:in `run'
	27: from /Users/rschneeman/.gem/ruby/2.7.0/gems/irb-1.2.1/lib/irb.rb:469:in `catch'
	26: from /Users/rschneeman/.gem/ruby/2.7.0/gems/irb-1.2.1/lib/irb.rb:470:in `block in run'
	25: from /Users/rschneeman/.gem/ruby/2.7.0/gems/irb-1.2.1/lib/irb.rb:535:in `eval_input'
	24: from /Users/rschneeman/.gem/ruby/2.7.0/gems/irb-1.2.1/lib/irb/ruby-lex.rb:134:in `each_top_level_statement'
	23: from /Users/rschneeman/.gem/ruby/2.7.0/gems/irb-1.2.1/lib/irb/ruby-lex.rb:134:in `catch'
	22: from /Users/rschneeman/.gem/ruby/2.7.0/gems/irb-1.2.1/lib/irb/ruby-lex.rb:135:in `block in each_top_level_statement'
	21: from /Users/rschneeman/.gem/ruby/2.7.0/gems/irb-1.2.1/lib/irb/ruby-lex.rb:135:in `loop'
	20: from /Users/rschneeman/.gem/ruby/2.7.0/gems/irb-1.2.1/lib/irb/ruby-lex.rb:138:in `block (2 levels) in each_top_level_statement'
	19: from /Users/rschneeman/.gem/ruby/2.7.0/gems/irb-1.2.1/lib/irb/ruby-lex.rb:166:in `lex'
	18: from /Users/rschneeman/.gem/ruby/2.7.0/gems/irb-1.2.1/lib/irb.rb:516:in `block in eval_input'
	17: from /Users/rschneeman/.gem/ruby/2.7.0/gems/irb-1.2.1/lib/irb.rb:693:in `signal_status'
	16: from /Users/rschneeman/.gem/ruby/2.7.0/gems/irb-1.2.1/lib/irb.rb:517:in `block (2 levels) in eval_input'
	15: from /Users/rschneeman/.gem/ruby/2.7.0/gems/irb-1.2.1/lib/irb/input-method.rb:258:in `gets'
	14: from /Users/rschneeman/.rubies/ruby-2.7.0/lib/ruby/2.7.0/forwardable.rb:235:in `readmultiline'
	13: from /Users/rschneeman/.rubies/ruby-2.7.0/lib/ruby/2.7.0/forwardable.rb:235:in `readmultiline'
	12: from /Users/rschneeman/.rubies/ruby-2.7.0/lib/ruby/2.7.0/reline.rb:170:in `readmultiline'
	11: from /Users/rschneeman/.rubies/ruby-2.7.0/lib/ruby/2.7.0/reline.rb:232:in `inner_readline'
	10: from /Users/rschneeman/.rubies/ruby-2.7.0/lib/ruby/2.7.0/reline.rb:232:in `loop'
	 9: from /Users/rschneeman/.rubies/ruby-2.7.0/lib/ruby/2.7.0/reline.rb:233:in `block in inner_readline'
	 8: from /Users/rschneeman/.rubies/ruby-2.7.0/lib/ruby/2.7.0/reline.rb:262:in `read_io'
	 7: from /Users/rschneeman/.rubies/ruby-2.7.0/lib/ruby/2.7.0/reline.rb:262:in `loop'
	 6: from /Users/rschneeman/.rubies/ruby-2.7.0/lib/ruby/2.7.0/reline.rb:303:in `block in read_io'
	 5: from /Users/rschneeman/.rubies/ruby-2.7.0/lib/ruby/2.7.0/reline.rb:234:in `block (2 levels) in inner_readline'
	 4: from /Users/rschneeman/.rubies/ruby-2.7.0/lib/ruby/2.7.0/reline.rb:234:in `each'
	 3: from /Users/rschneeman/.rubies/ruby-2.7.0/lib/ruby/2.7.0/reline.rb:235:in `block (3 levels) in inner_readline'
	 2: from /Users/rschneeman/.rubies/ruby-2.7.0/lib/ruby/2.7.0/reline/line_editor.rb:835:in `input_key'
	 1: from /Users/rschneeman/.rubies/ruby-2.7.0/lib/ruby/2.7.0/reline/line_editor.rb:855:in `process_auto_indent'
/Users/rschneeman/.rubies/ruby-2.7.0/lib/ruby/2.7.0/reline/line_editor.rb:855:in `*': negative argument (ArgumentError)
```

## Terminal Emulator

iterm2 on a mac

```
$ irb -v
irb 1.2.1 (2019-12-24)
$ ruby -v
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin17]
```

**Comment by nobu** [comment]
It worked with the master.

```
irb(main):001:1* class Foo
irb(main):002:1*   
irb(main):003:2*   def foo?
irb(main):004:1*   end
irb(main):005:0> end
=> :foo?
irb(main):006:0> 
irb(main):007:0> f = Foo.new
irb(main):008:0> 
irb(main):009:0> require 'benchmark/ips'
=> true
irb(main):010:0> 
irb(main):011:1* Benchmark.ips do |x|
irb(main):012:2*   x.report("respond_to") {
irb(main):013:2*     f.respond_to?(:foo?)
irb(main):014:1*     }
irb(main):015:2*     x.report("is_a?") { 
irb(main):016:2*       f.is_a?(Foo)
irb(main):017:1*       }
irb(main):018:1*       x.compare!
irb(main):019:0> end
```

But the indentation in `ips` block seems wrong.

**Comment by schneems** [comment]
Thank you for checking!

Yes, that does look incorrect. The indentation is not correct on both. Should I update the title to make this issue about indentation?
