### ISSUE TITLE
IRB runs out of memory when inspecting lots of data

### ISSUE THREAD

**Issue by phansch** [ruby/irb#82]
## Description

This happened in the context of printing ~50000 large ActiveRecord objects (45 attributes) in a Rails 5.1 App, but here's a reproducer with plain Ruby:

```ruby
'abc' * 20_000_000
```

Executing that in IRB results in this traceback on my machine:

```
Traceback (most recent call last):
   16: from /home/<user>/.gem/ruby/2.6.5/gems/irb-1.2.3/lib/irb.rb:399:in `start'
   15: from /home/<user>/.gem/ruby/2.6.5/gems/irb-1.2.3/lib/irb.rb:470:in `run'
   14: from /home/<user>/.gem/ruby/2.6.5/gems/irb-1.2.3/lib/irb.rb:470:in `catch'
   13: from /home/<user>/.gem/ruby/2.6.5/gems/irb-1.2.3/lib/irb.rb:471:in `block in run'
   12: from /home/<user>/.gem/ruby/2.6.5/gems/irb-1.2.3/lib/irb.rb:536:in `eval_input'
   11: from /home/<user>/.gem/ruby/2.6.5/gems/irb-1.2.3/lib/irb/ruby-lex.rb:134:in `each_top_level_statement'
   10: from /home/<user>/.gem/ruby/2.6.5/gems/irb-1.2.3/lib/irb/ruby-lex.rb:134:in `catch'
    9: from /home/<user>/.gem/ruby/2.6.5/gems/irb-1.2.3/lib/irb/ruby-lex.rb:135:in `block in each_top_level_statement'
    8: from /home/<user>/.gem/ruby/2.6.5/gems/irb-1.2.3/lib/irb/ruby-lex.rb:135:in `loop'
    7: from /home/<user>/.gem/ruby/2.6.5/gems/irb-1.2.3/lib/irb/ruby-lex.rb:150:in `block (2 levels) in each_top_level_statement'
    6: from /home/<user>/.gem/ruby/2.6.5/gems/irb-1.2.3/lib/irb.rb:537:in `block in eval_input'
    5: from /home/<user>/.gem/ruby/2.6.5/gems/irb-1.2.3/lib/irb.rb:694:in `signal_status'
    4: from /home/<user>/.gem/ruby/2.6.5/gems/irb-1.2.3/lib/irb.rb:541:in `block (2 levels) in eval_input'
    3: from /home/<user>/.gem/ruby/2.6.5/gems/irb-1.2.3/lib/irb.rb:741:in `output_value'
    2: from /home/<user>/.gem/ruby/2.6.5/gems/irb-1.2.3/lib/irb.rb:741:in `!~'
    1: from /home/<user>/.gem/ruby/2.6.5/gems/irb-1.2.3/lib/irb.rb:741:in `=~'
RegexpError (failed to allocate memory: /\A.*\Z/)

```

This works fine in `pry` and might be because I'm using irb 1.2.3 with Ruby 2.6.5, instead of Ruby 2.7.

## Terminal Emulator

URVXT

## Other system info

Memory: 16GB
OS: Xubuntu 18.04

Let me know if you need any more information.

**Comment by aycabta** [comment]
I couldn't reproduce it because I guess my machine has enough memory, but I created https://github.com/ruby/irb/pull/83. You can try again with this patch applied `/home/<user>/.gem/ruby/2.6.5/gems/irb-1.2.3/lib/irb.rb:741`.

**Comment by phansch** [comment]
@aycabta I applied the patch locally and that fixes the problem :tada: thank you!
