### ISSUE TITLE
IRB 1.2.3 does not boot with Ruby 2.7 on my mac

### ISSUE THREAD

**Issue by schneems** [ruby/irb#87]
## Description

Here is the output:

```
$ irb -v
irb 1.2.3 (2020-02-15)
⛄ 2.7.0 🚀  ~/Documents/projects/heroku-buildpack-ruby (master)
$ ruby -v
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin17]
⛄ 2.7.0 🚀  ~/Documents/projects/heroku-buildpack-ruby (master)
$ irb
Traceback (most recent call last):
	9: from /Users/rschneeman/.gem/ruby/2.7.0/bin/irb:23:in `<main>'
	8: from /Users/rschneeman/.gem/ruby/2.7.0/bin/irb:23:in `load'
	7: from /Users/rschneeman/.gem/ruby/2.7.0/gems/irb-1.2.3/exe/irb:11:in `<top (required)>'
	6: from /Users/rschneeman/.gem/ruby/2.7.0/gems/irb-1.2.3/lib/irb.rb:397:in `start'
	5: from /Users/rschneeman/.gem/ruby/2.7.0/gems/irb-1.2.3/lib/irb.rb:397:in `new'
	4: from /Users/rschneeman/.gem/ruby/2.7.0/gems/irb-1.2.3/lib/irb.rb:455:in `initialize'
	3: from /Users/rschneeman/.gem/ruby/2.7.0/gems/irb-1.2.3/lib/irb.rb:455:in `new'
	2: from /Users/rschneeman/.gem/ruby/2.7.0/gems/irb-1.2.3/lib/irb/context.rb:86:in `initialize'
	1: from /Users/rschneeman/.gem/ruby/2.7.0/gems/irb-1.2.3/lib/irb/context.rb:86:in `new'
/Users/rschneeman/.gem/ruby/2.7.0/gems/irb-1.2.3/lib/irb/input-method.rb:213:in `initialize': undefined method `encoding_system_needs' for Reline:Module (NoMethodError)
```

## Terminal Emulator

iTerm2
Mac 10.13.6
I use chruby for my version selection

**Comment by NathanUrwin** [comment]
I'm encountering the same issue. I used brew to install ruby.

```bash
$ irb --verbose
Switch to inspect mode.
Traceback (most recent call last):
	9: from /usr/local/lib/ruby/gems/2.7.0/bin/irb:23:in `<main>'
	8: from /usr/local/lib/ruby/gems/2.7.0/bin/irb:23:in `load'
	7: from /usr/local/lib/ruby/gems/2.7.0/gems/irb-1.2.3/exe/irb:11:in `<top (required)>'
	6: from /usr/local/lib/ruby/gems/2.7.0/gems/irb-1.2.3/lib/irb.rb:397:in `start'
	5: from /usr/local/lib/ruby/gems/2.7.0/gems/irb-1.2.3/lib/irb.rb:397:in `new'
	4: from /usr/local/lib/ruby/gems/2.7.0/gems/irb-1.2.3/lib/irb.rb:455:in `initialize'
	3: from /usr/local/lib/ruby/gems/2.7.0/gems/irb-1.2.3/lib/irb.rb:455:in `new'
	2: from /usr/local/lib/ruby/gems/2.7.0/gems/irb-1.2.3/lib/irb/context.rb:86:in `initialize'
	1: from /usr/local/lib/ruby/gems/2.7.0/gems/irb-1.2.3/lib/irb/context.rb:86:in `new'
/usr/local/lib/ruby/gems/2.7.0/gems/irb-1.2.3/lib/irb/input-method.rb:213:in `initialize': undefined method `encoding_system_needs' for Reline:Module (NoMethodError)
```

**Comment by tsprlng** [comment]
For me, `gem install reline` fixed it -- not sure though why `irb`'s dependency on it wasn't enough.

**Comment by NathanUrwin** [comment]
Hey @tsprlng :wave:

That fixed it for me, thanks! :tada:

**Comment by aycabta** [comment]
Thank you for reporting and teaching the solution!
