### ISSUE TITLE
Crash with Hash with non-UTF8 key

### ISSUE THREAD

**Issue by k0kubun** [ruby/irb#92]
### Expected
Raise EncodingError (and shown by irb), but irb doesn't stop

### Actual
When I tried to input `{"device \xAE": 1}`,

```
$ RUBYOPT=-v irb
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin18]
irb(main)[01:0]> IRB::VERSION
=> "1.2.1"
irb(main)[02:1]* {"device \xAE": Traceback (most recent call last):
        37: from /Users/k0kubun/.rbenv/versions/2.7.0/bin/irb:23:in `<main>'
        36: from /Users/k0kubun/.rbenv/versions/2.7.0/bin/irb:23:in `load'
        35: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/irb-1.2.1/exe/irb:11:in `<top (required)>'
        34: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/irb.rb:398:in `start'
        33: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/irb.rb:469:in `run'
        32: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/irb.rb:469:in `catch'
        31: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/irb.rb:470:in `block in run'
        30: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/irb.rb:535:in `eval_input'
        29: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/irb/ruby-lex.rb:134:in `each_top_level_statement'
        28: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/irb/ruby-lex.rb:134:in `catch'
        27: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/irb/ruby-lex.rb:135:in `block in each_top_level_statement'
        26: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/irb/ruby-lex.rb:135:in `loop'
        25: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/irb/ruby-lex.rb:138:in `block (2 levels) in each_top_level_statement'
        24: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/irb/ruby-lex.rb:166:in `lex'
        23: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/irb.rb:516:in `block in eval_input'
        22: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/irb.rb:693:in `signal_status'
        21: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/irb.rb:517:in `block (2 levels) in eval_input'
        20: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/irb/input-method.rb:258:in `gets'
        19: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/forwardable.rb:235:in `readmultiline'
        18: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/forwardable.rb:235:in `readmultiline'
        17: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/reline.rb:170:in `readmultiline'
        16: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/reline.rb:232:in `inner_readline'
        15: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/reline.rb:232:in `loop'
        14: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/reline.rb:233:in `block in inner_readline'
        13: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/reline.rb:262:in `read_io'
        12: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/reline.rb:262:in `loop'
        11: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/reline.rb:303:in `block in read_io'
        10: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/reline.rb:234:in `block (2 levels) in inner_readline'
         9: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/reline.rb:234:in `each'
         8: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/reline.rb:236:in `block (3 levels) in inner_readline'
         7: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/reline/line_editor.rb:330:in `rerender'
         6: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/reline/line_editor.rb:77:in `check_multiline_prompt'
         5: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/irb/ruby-lex.rb:50:in `block in set_input'
         4: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/irb/ruby-lex.rb:50:in `each_index'
         3: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/irb/ruby-lex.rb:52:in `block (2 levels) in set_input'
         2: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/irb/ruby-lex.rb:113:in `check_state'
         1: from /Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/irb/ruby-lex.rb:212:in `check_code_block'
/Users/k0kubun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/irb/ruby-lex.rb:212:in `compile': invalid symbol in encoding UTF-8 :"device \\xAE" (EncodingError)
```

## Terminal Emulator

macOS Terminal.app

**Comment by aycabta** [comment]
This is fixed by https://github.com/ruby/irb/commit/13572d8cdcc31d63f7c1fe6af8e892a60c5727ab.

**Comment by k0kubun** [comment]
Thank you!
